// Aqeedah Data: Al-Wasitiyya (1-22), Al-Tahawiyya (2-20), Beginners (1-14)

const mk = (bookId:string, n:number, title:string, titleAr:string, desc:string, arabic:string, trans:string, note:string,
  vocab:Array<{arabic:string;transliteration:string;english:string;pos:string}>,
  gTitle:string, gTitleAr:string, gExp:string, gEx:{arabic:string;translation:string},
  q1:{q:string;opts:string[];a:number}, q2:{q:string;opts:string[];a:number}) => ({
  bookId, lessonNum:n, title, titleArabic:titleAr, description:desc,
  pages:[{id:1, arabic, translation:trans, transliteration:"", note}],
  vocabulary:vocab,
  grammar:{title:gTitle, titleArabic:gTitleAr, explanation:gExp, examples:[gEx]},
  exercises:[{type:"choose" as const, instruction:`Quiz: ${title}`, instructionArabic:`اسْأَلِ عَنْ: ${titleAr}`,
    items:[{question:q1.q,options:q1.opts,answer:q1.a},{question:q2.q,options:q2.opts,answer:q2.a}],
    answers:[q1.a,q2.a]}]
});

// ─── AL-AQEEDAH AL-WASITIYYA (Ibn Taymiyyah) — Lessons 1–22 ───────────────

export const aqeedahData = [

mk("aqeedah-wasitiyya",1,"Introduction to Al-Aqeedah Al-Wasitiyya","مُقَدِّمَةٌ فِي العَقِيدَةِ الوَاسِطِيَّة",
"Ibn Taymiyyah's foundational creed text — why aqeedah matters and what it contains.",
"الإِمَامُ ابْنُ تَيْمِيَّة (٦٦١–٧٢٨ هـ):\nأَلَّفَ «العَقِيدَةَ الوَاسِطِيَّة» رَدًّا عَلَى طَلَبِ أَهْلِ وَاسِط (بَلَد فِي العِرَاق)\n\nمَوْضُوعُهَا:\n• إِثْبَاتُ الأَسْمَاءِ وَالصِّفَاتِ لِلَّهِ عَلَى ظَاهِرِهَا مِنْ غَيْرِ تَأْوِيل وَلَا تَعْطِيل\n• مَنْهَجُ أَهْلِ السُّنَّةِ وَالجَمَاعَة\n\nالعَقِيدَة لُغَةً: مِنَ العَقْدِ — الشَّيْءُ الَّذِي «يَعْقِدُهُ» القَلْبُ وَيُوثِقُهُ\nاصْطِلَاحًا: مَجْمُوعَةُ الحَقَائِقِ اليَقِينِيَّةِ الَّتِي يُؤْمِنُ بِهَا المُسْلِم",
"Imam Ibn Taymiyyah (661–728 AH):\nWrote 'Al-Aqeedah Al-Wasitiyyah' in response to a request from the people of Wasit, Iraq\n\nIts subject:\n• Affirming Allah's Names and Attributes as they appear — without distortion or denial\n• The methodology of Ahl al-Sunnah wa-l-Jama'ah\n\nAqeedah linguistically: from 'aqd' (knot/tie) — what the heart 'ties' and commits to firmly\nAs terminology: the collection of certain truths that a Muslim believes",
"ابْنُ تَيْمِيَّة كَتَبَهَا فِي يَوْم وَاحِد — ثُمَّ نُوقِشَتْ بَيْنَ العُلَمَاء. أَهَمِّيَّتُهَا: تَجْمَعُ العَقِيدَة الصَّحِيحَة فِي رِسَالَة صَغِيرَة مَحْكَمَة.",
[{arabic:"عَقِيدَة",transliteration:"ʿaqīdah",english:"Islamic creed/article of faith",pos:"noun (f)"},
 {arabic:"عَقَّدَ",transliteration:"ʿaqqada",english:"tied firmly/committed (heart to a belief)",pos:"verb (past)"},
 {arabic:"أَسْمَاء وَصِفَات",transliteration:"asmāʾ wa ṣifāt",english:"Names and Attributes (of Allah)",pos:"noun phrase"},
 {arabic:"تَأْوِيل",transliteration:"taʾwīl",english:"reinterpretation/distortion of meaning",pos:"noun (m)"},
 {arabic:"تَعْطِيل",transliteration:"taʿṭīl",english:"denial/stripping of attributes",pos:"noun (m)"}],
"Why Aqeedah is the Foundation","لِمَاذَا العَقِيدَةُ هِيَ الأَسَاس",
"Al-Aqeedah precedes everything else:\n• Correct aqeedah = accepted deeds\n• Wrong aqeedah = all deeds may be rejected\n\nThe Quran was revealed 13 years in Makkah — mostly aqeedah.\nOnly in Madinah did detailed fiqh (law) come.\nOrder: BELIEF → WORSHIP → LAW\n\nIbn Taymiyyah's methodology: text (naql) + intellect (aql) — together, not opposed.",
{arabic:"«التَّوْحِيدُ أَوَّلًا» — دَعْوَةُ كُلِّ نَبِيّ",translation:"'Tawhid first' — the call of every prophet (starting point of every prophetic message)"},
{q:"What does 'aqeedah' literally mean?",opts:["Prayer","What the heart firmly ties itself to and commits to","A book of law","A type of worship"],a:1},
{q:"Ibn Taymiyyah's method in aqeedah was:",opts:["Reason alone","Text (Quran/Sunnah) alone","Text AND sound reason together — without distorting one for the other","Following Greek philosophy"],a:2}),

mk("aqeedah-wasitiyya",2,"Tawhid al-Rububiyyah — Lordship","تَوْحِيدُ الرُّبُوبِيَّة",
"Believing Allah alone is the Lord — Creator, Sustainer, Controller of all existence.",
"تَوْحِيدُ الرُّبُوبِيَّة:\nاعْتِقَادُ أَنَّ اللهَ وَحْدَهُ هُوَ:\n• الخَالِق: ﴿أَلَا لَهُ الخَلْقُ وَالأَمْر﴾ [الأعراف: ٥٤]\n• الرَّازِق: ﴿إِنَّ اللهَ هُوَ الرَّزَّاقُ ذُو القُوَّةِ المَتِين﴾ [الذاريات: ٥٨]\n• المُدَبِّر: ﴿يُدَبِّرُ الأَمْرَ مِنَ السَّمَاءِ إِلَى الأَرْض﴾ [السجدة: ٥]\n• المُحْيِي المُمِيت: ﴿هُوَ يُحْيِي وَيُمِيتُ﴾\n\nأَقَرَّ بِهَا حَتَّى المُشْرِكُون: ﴿وَلَئِنْ سَأَلْتَهُمْ مَنْ خَلَقَ السَّمَاوَاتِ وَالأَرْضَ لَيَقُولُنَّ اللهُ﴾",
"Tawhid al-Rububiyyah:\nBelieving Allah alone is:\n• The Creator: 'To Him belongs creation and command.' [7:54]\n• The Provider: 'Allah is the All-Provider, Owner of Power, the Strong.' [51:58]\n• The Manager: 'He directs the matter from the sky to the earth.' [32:5]\n• The Giver/Taker of Life: 'He gives life and causes death.'\n\nEven the polytheists acknowledged this: 'If you ask them who created the heavens and earth, they say: Allah.'",
"الرُّبُوبِيَّةُ وَحْدَهَا لَا تَكْفِي — قُرَيْش أَقَرَّتْ بِهَا وَلَمْ تَنْجُ. المَطْلُوبُ: تَوْحِيدُ الأُلُوهِيَّة (العِبَادَة) — أَنْ تُفْرِدَ اللهَ بِالعِبَادَة كَمَا أَفْرَدْتَهُ بِالخَلْق.",
[{arabic:"رُبُوبِيَّة",transliteration:"rubūbiyyah",english:"Lordship (Allah's sole authority over creation)",pos:"noun (f)"},
 {arabic:"خَالِق",transliteration:"khāliq",english:"Creator",pos:"noun (m)"},
 {arabic:"رَزَّاق",transliteration:"razzāq",english:"All-Provider",pos:"noun (m)"},
 {arabic:"مُدَبِّر",transliteration:"mudabbir",english:"Manager/Director (of affairs)",pos:"noun (m)"},
 {arabic:"مُحْيِي",transliteration:"muḥyī",english:"Giver of Life",pos:"noun (m)"}],
"Three Types of Tawhid","أَنْوَاعُ التَّوْحِيدِ الثَّلَاثَة",
"The scholars of Ahl al-Sunnah divide Tawhid into three:\n1. Rububiyyah = Lordship (who CONTROLS the universe)\n2. Uluhiyyah = Divinity (who DESERVES worship)\n3. Asma' wa Sifat = Names and Attributes (how Allah DESCRIBES Himself)\n\nAll three must be affirmed. Missing any one is deficiency in Tawhid.",
{arabic:"الرُّبُوبِيَّة + الأُلُوهِيَّة + الأَسْمَاء وَالصِّفَات = التَّوْحِيدُ الكَامِل",translation:"Lordship + Divinity + Names & Attributes = Complete Tawhid"},
{q:"Tawhid al-Rububiyyah means:",opts:["Praying 5 times daily","Believing Allah alone is the Creator, Provider, and Controller of all existence","Paying Zakah","Fasting Ramadan"],a:1},
{q:"Why was Quraysh's acknowledgment of Rububiyyah not enough to save them?",opts:["They didn't believe it sincerely","They acknowledged Allah created everything but still directed their worship to idols — missing Tawhid al-Uluhiyyah","They were Arabs","They didn't pray"],a:1}),

mk("aqeedah-wasitiyya",3,"Tawhid al-Uluhiyyah — Worship","تَوْحِيدُ الأُلُوهِيَّة",
"The most important type — singling out Allah alone for all acts of worship.",
"تَوْحِيدُ الأُلُوهِيَّة:\nإِفْرَادُ اللهِ بِجَمِيعِ أَنْوَاعِ العِبَادَة:\n• الصَّلَاة، الصَّوْم، الحَجّ\n• الدُّعَاء: «الدُّعَاءُ هُوَ العِبَادَة» — قَالَهُ النَّبِيُّ ﷺ\n• الخَوْف وَالرَّجَاء\n• المَحَبَّة الكَامِلَة\n• الذَّبْح وَالنَّذْر\n\nلَا إِلَهَ إِلَّا اللهُ = لَا مَعْبُودَ بِحَقٍّ إِلَّا اللهُ\nرُكْنَاهَا:\n• النَّفْيُ: لَا إِلَهَ (نَفْيُ الأُلُوهِيَّة عَنْ كُلِّ مَا سِوَى اللهِ)\n• الإِثْبَاتُ: إِلَّا اللهُ (إِثْبَاتُهَا للهِ وَحْدَهُ)",
"Tawhid al-Uluhiyyah:\nSingling out Allah for ALL types of worship:\n• Prayer, Fasting, Hajj\n• Du'a: 'Du'a IS worship.' — Prophet ﷺ\n• Fear and Hope\n• Complete Love\n• Slaughter and vows\n\nLa ilaha illa Allah = There is no deity worthy of worship except Allah\nIts two pillars:\n• Negation: La ilaha (denying divinity to everything besides Allah)\n• Affirmation: Illa Allah (affirming it for Allah alone)",
"هَذَا هُوَ التَّوْحِيدُ الَّذِي جَاءَتْ بِهِ الرُّسُل — «لَا إِلَهَ إِلَّا اللهُ» كَلِمَةٌ عَظِيمَةٌ: نَفْيٌ وَإِثْبَات — نَفْيُ كُلِّ مَعْبُود وَإِثْبَاتٌ لِلْمَعْبُودِ الحَقّ.",
[{arabic:"أُلُوهِيَّة",transliteration:"ulūhiyyah",english:"Divinity (right to be worshipped)",pos:"noun (f)"},
 {arabic:"إِفْرَاد",transliteration:"ifrād",english:"singling out (Allah for worship)",pos:"noun (m)"},
 {arabic:"نَفْي",transliteration:"nafy",english:"negation/denial",pos:"noun (m)"},
 {arabic:"إِثْبَات",transliteration:"ithbāt",english:"affirmation",pos:"noun (m)"},
 {arabic:"شِرْك",transliteration:"shirk",english:"associating partners with Allah in worship",pos:"noun (m)"}],
"La ilaha illa Allah — Negation then Affirmation","لَا إِلَهَ إِلَّا اللهُ — نَفْيٌ ثُمَّ إِثْبَات",
"The structure is intentional:\n1. FIRST negate: 'La ilaha' — no deity (clears the field of all false gods)\n2. THEN affirm: 'Illa Allah' — except Allah alone\n\nNot: 'Allah is God' (pure affirmation) — that would allow others alongside.\nNot: 'No god' (pure negation) — that's atheism.\nBut: 'No god EXCEPT Allah' — complete exclusive Tawhid.",
{arabic:"«الدُّعَاءُ هُوَ العِبَادَة» ثُمَّ تَلَا: ﴿وَقَالَ رَبُّكُمُ ادْعُونِي أَسْتَجِبْ لَكُمْ﴾",translation:"'Du'a IS worship' then recited: 'Your Lord says: Call on Me, I will respond to you.' [40:60]"},
{q:"Directing du'a to other than Allah is:",opts:["Permissible if sincere","Shirk — violating Tawhid al-Uluhiyyah, since du'a is worship","Allowed for intermediaries","Only forbidden for idols"],a:1},
{q:"La ilaha illa Allah contains:",opts:["Only affirmation","Only negation","Negation of all false deities THEN affirmation of Allah alone — both required","Historical statement only"],a:2}),

mk("aqeedah-wasitiyya",4,"Tawhid al-Asma' wa-l-Sifat — Names & Attributes","تَوْحِيدُ الأَسْمَاءِ وَالصِّفَات",
"Affirming Allah's beautiful Names and Attributes as He described Himself — without distortion, denial, resemblance, or asking how.",
"أَهْلُ السُّنَّةِ وَسَطٌ بَيْنَ طَرَفَيْن:\n\nالتَّعْطِيل (المُعْطِلَة): نَفْيُ الصِّفَات — «لَيْسَ لِلَّهِ يَدٌ — بَلِ المُرَادُ: نِعْمَتُهُ» ← بَاطِل\n\nالتَّمْثِيل (المُجَسِّمَة): تَشْبِيهُ الصِّفَات بِالمَخْلُوق ← بَاطِل\n\nالوَسَطُ الصَّحِيح:\nإِثْبَاتُ الصِّفَاتِ عَلَى الحَقِيقَةِ دُونَ تَأْوِيل وَدُونَ تَشْبِيه\n﴿لَيْسَ كَمِثْلِهِ شَيْءٌ وَهُوَ السَّمِيعُ البَصِير﴾ [الشورى: ١١]\n\nالمَنْهَجُ: أَمِرُّوهَا كَمَا جَاءَتْ — «بِلَا كَيْف»",
"Ahl al-Sunnah are the middle path between two extremes:\n\nTa'til (Deniers): Denying attributes — 'Allah has no Hand — 'hand' means His blessing' ← false\n\nTamthil (Anthropomorphists): Likening attributes to creation ← false\n\nThe Correct Middle:\nAffirm the attributes as real without distorting or resembling to creation\n'There is nothing like Him, yet He is the All-Hearing, All-Seeing.' [42:11]\n\nThe method: Pass them as they came — 'without asking how (bila kayf)'",
"«بِلَا كَيْفَ وَلَا مَعْنَى وَلَا تَشْبِيه» — الإِمَامُ مَالِك عِنْدَمَا سُئِلَ عَنِ الاسْتِوَاء. الصِّفَاتُ مَعْلُومَةٌ — وَالكَيْفِيَّةُ مَجْهُولَة — وَالسُّؤَالُ بِدْعَة.",
[{arabic:"صِفَة",transliteration:"ṣifah",english:"attribute/characteristic",pos:"noun (f)"},
 {arabic:"تَعْطِيل",transliteration:"taʿṭīl",english:"denial of attributes",pos:"noun (m)"},
 {arabic:"تَمْثِيل",transliteration:"tamthīl",english:"anthropomorphism (likening to creation)",pos:"noun (m)"},
 {arabic:"بِلَا كَيْف",transliteration:"bilā kayf",english:"without asking 'how'",pos:"phrase"},
 {arabic:"اسْتِوَاء",transliteration:"istiwāʾ",english:"rising/establishing (over the Throne)",pos:"noun (m)"}],
"The Golden Rule of Ahl al-Sunnah on Attributes","القَاعِدَةُ الذَّهَبِيَّة فِي الصِّفَات",
"Imam Malik's answer when asked about 'Istawā' (rose/established):\n'Al-Istawā is known, the how is unknown, belief in it is obligatory, and asking about it is innovation (bid'ah).'\n\nFour conditions for affirming attributes:\n1. No distortion of meaning (تأويل)\n2. No complete denial (تعطيل)\n3. No resemblance to creation (تمثيل)\n4. No asking how (تكييف)",
{arabic:"«الاسْتِوَاءُ مَعْلُومٌ وَالكَيْفُ مَجْهُولٌ وَالإِيمَانُ بِهِ وَاجِبٌ وَالسُّؤَالُ عَنْهُ بِدْعَة» — الإِمَامُ مَالِك",translation:"'Rising (istiwā') is known, the how is unknown, belief in it is obligatory, and asking about it is innovation.' — Imam Malik's famous response"},
{q:"What is ta'til (تعطيل) in aqeedah?",opts:["Affirming all attributes as they are","Denying or reinterpreting Allah's attributes away from their real meaning","Comparing Allah to creation","Asking how the attributes are"],a:1},
{q:"'Bila kayf' (without asking how) means:",opts:["We don't know Arabic","We affirm the attribute as real but don't assign a 'how' or form to it","We deny the attribute","We make it metaphorical"],a:1}),

...["Allah's Names — Al-Hayy Al-Qayyum","Allah's Names — Al-Alim Al-Khabir","Allah's Names — Al-Qadir Al-Aziz",
"Allah's Speech and the Quran","Seeing Allah in the Hereafter","Belief in the Angels",
"Belief in the Scriptures","Belief in the Prophets","Belief in the Last Day",
"Belief in Qadar (Divine Decree)","Al-Firqah al-Najiyah — The Saved Sect",
"The Companions of the Prophet ﷺ","Love of Ahl al-Bayt",
"Political Leadership in Islam","Rights of Fellow Muslims",
"Karamat — Miracles of the Righteous","Conclusion and Final Review"]
.map((title,i) => {
  const n = i+5;
  const titleAr = ["أَسْمَاءُ اللهِ — الحَيُّ القَيُّوم","أَسْمَاءُ اللهِ — العَلِيمُ الخَبِير","أَسْمَاءُ اللهِ — القَادِرُ العَزِيز",
    "كَلَامُ اللهِ وَالقُرْآن","رُؤْيَةُ اللهِ فِي الآخِرَة","الإِيمَانُ بِالمَلَائِكَة",
    "الإِيمَانُ بِالكُتُب","الإِيمَانُ بِالأَنْبِيَاء","الإِيمَانُ بِاليَوْمِ الآخِر",
    "الإِيمَانُ بِالقَدَر","الفِرْقَةُ النَّاجِيَة","الصَّحَابَةُ الكِرَام",
    "حُبُّ آلِ البَيْت","القِيَادَةُ السِّيَاسِيَّة","حُقُوقُ المُسْلِمِين",
    "الكَرَامَات","الخَاتِمَة وَالمُرَاجَعَة"][i];
  return mk("aqeedah-wasitiyya",n,title,titleAr,`Al-Wasitiyya Lesson ${n}: ${title}`,
    `الدَّرْسُ ${n} — ${titleAr}\n\nمَنْهَجُ أَهْلِ السُّنَّةِ وَالجَمَاعَة:\n«مَا أَنَا عَلَيْهِ وَأَصْحَابِي» — النَّبِيُّ ﷺ\n\nالاعْتِصَامُ بِالكِتَابِ وَالسُّنَّةِ وَإِجْمَاعِ السَّلَف — هَذَا هُوَ الطَّرِيقُ الآمِن.`,
    `Lesson ${n} — ${title}\n\nThe methodology of Ahl al-Sunnah:\n'What I am upon and my companions' — Prophet ﷺ\n\nHolding firm to Quran, Sunnah, and consensus of the Salaf — this is the safe path.`,
    `هَذَا الدَّرْسُ يُعَمِّقُ فَهْمَنَا لِعَقِيدَةِ أَهْلِ السُّنَّةِ الصَّحِيحَة.`,
    [{arabic:"عَقِيدَة",transliteration:"ʿaqīdah",english:"creed/article of faith",pos:"noun (f)"},
     {arabic:"سُنَّة",transliteration:"sunnah",english:"Prophetic way",pos:"noun (f)"},
     {arabic:"سَلَف",transliteration:"salaf",english:"pious predecessors (first 3 generations)",pos:"noun (m)"},
     {arabic:"إِجْمَاع",transliteration:"ijmāʿ",english:"consensus of scholars",pos:"noun (m)"},
     {arabic:"نَجَاة",transliteration:"najāh",english:"salvation",pos:"noun (f)"}],
    "Ahl al-Sunnah wa-l-Jama'ah","أَهْلُ السُّنَّةِ وَالجَمَاعَة",
    `Ahl al-Sunnah are defined by:\n1. Following Quran and Sunnah\n2. Following the way of the companions\n3. Avoiding innovations\n4. Being the middle nation between extremes\n\nLesson ${n} builds this understanding in the context of ${title}.`,
    {arabic:"«عَلَيْكُمْ بِالجَمَاعَةِ فَإِنَّ يَدَ اللهِ مَعَ الجَمَاعَة»",translation:"'Hold to the community — for Allah's hand is with the united community.'"},
    {q:`What is the primary source for correct aqeedah?`,opts:["Greek philosophy","Quran, Sunnah, and the understanding of the Companions (Salaf)","Personal interpretation","Only the intellect"],a:1},
    {q:`The Salaf are defined as:`,opts:["Muslims who lived 1,000 years ago","The first three generations: Companions, Successors, and their Successors","Only the Companions","Scholars of hadith only"],a:1});
}),

// ─── AL-AQEEDAH AL-TAHAWIYYA — Lessons 2–20 ───────────────────────────────

...["The Essence of Allah Beyond Human Comprehension",
  "Qadar — Six Aspects of Divine Decree","Allah's Will vs Human Free Will",
  "The Quran — Allah's Eternal Word","The Scale, Basin and Accounting",
  "Paradise and Hellfire","Intercession (Shafa'ah)","The Covenant — Al-Mithaq",
  "The Prophet Muhammad ﷺ — His Station","The Companions after the Prophet ﷺ",
  "The Basin (Hawd) of the Prophet ﷺ","The Sirat — Bridge over Hellfire",
  "Death, the Soul, and the Grave","Punishment and Blessing of the Grave",
  "The Resurrection and Great Gathering","Believers in Paradise Forever",
  "Political Obedience and Disagreement","Supplication for Muslim Leaders",
  "Final Comprehensive Review of Tahawiyya"]
.map((title,i) => {
  const n = i+2;
  const titleAr = ["ذَاتُ اللهِ فَوْقَ الإِدْرَاك","القَدَرُ — السِّتَّةُ الأَرْكَان","إِرَادَةُ اللهِ وَاخْتِيَارُ الإِنْسَان",
    "القُرْآنُ كَلَامُ اللهِ","المِيزَانُ وَالحِسَابُ وَالحَوْض",
    "الجَنَّةُ وَالنَّار","الشَّفَاعَة","المِيثَاقُ الأَزَلِيّ",
    "مَقَامُ النَّبِيِّ ﷺ","الصَّحَابَةُ بَعْدَ النَّبِيِّ ﷺ",
    "حَوْضُ النَّبِيِّ ﷺ","الصِّرَاطُ","المَوْتُ وَالرُّوحُ وَالقَبْر",
    "عَذَابُ القَبْرِ وَنَعِيمُهُ","البَعْثُ وَالحَشْر",
    "المُؤْمِنُون فِي الجَنَّة إِلَى الأَبَد","الطَّاعَةُ السِّيَاسِيَّة",
    "الدُّعَاءُ لِوُلَاةِ الأُمُور","المُرَاجَعَةُ الشَّامِلَة"][i];
  const descriptions = [
    "Allah's essence is utterly unlike any created thing — beyond full human comprehension.",
    "The six pillars of belief in Qadar: knowledge, writing, will, and creation.",
    "Reconciling Allah's complete will with genuine human free choice.",
    "The Quran is Allah's actual Speech — not created — and its recitation is from us.",
    "The scale that weighs deeds, the Basin of the Prophet ﷺ, and the accounting.",
    "Paradise and Hellfire exist now and are eternal — their realities and descriptions.",
    "Who can intercede? For whom? Types of intercession on Judgment Day.",
    "The primordial covenant between Allah and all souls before creation.",
    "The Prophet's ﷺ station: Maqam Mahmud, Shafa'ah, special knowledge.",
    "The position of the companions — all have divine pleasure — love them all.",
    "The Hawd (basin) given to the Prophet ﷺ — water whiter than snow.",
    "The bridge over Hellfire — crossing speeds vary by deeds — believers cross.",
    "The three questions in the grave — Munkar and Nakir — soul's journey.",
    "The reality of questioning and either punishment or blessing in the grave.",
    "The blowing of the trumpet, rising from graves, gathering at Mahshar.",
    "Believers enter Paradise never to exit — eternal joy — meeting Allah.",
    "Obedience to Muslim rulers — its conditions and limits.",
    "Du'a for leaders — prophetic practice — supporting good governance.",
    "Final review of Al-Tahawiyya's key points — comprehensive aqeedah summary."];
  return mk("aqeedah-tahawiyya",n,title,titleAr,descriptions[i]||`Tahawiyya Lesson ${n}`,
    `الإِمَامُ الطَّحَاوِيّ (٢٣٩–٣٢١ هـ):\n\nمِنْ أَهَمِّ مَتْنِ «العَقِيدَةِ الطَّحَاوِيَّة» فِي الدَّرْسِ ${n}:\n\n«وَمَا أَخْطَأَ العَبْدَ لَمْ يَكُنْ لِيُصِيبَهُ — وَمَا أَصَابَهُ لَمْ يَكُنْ لِيُخْطِئَهُ»\n\nالعَقِيدَةُ الطَّحَاوِيَّةُ: مَتْنٌ مَقْبُولٌ لَدَى أَهْلِ السُّنَّةِ — جَمَعَ إِجْمَاعَ أَهْلِ السُّنَّةِ الكِرَام\n\nمَوْضُوعُ هَذَا الدَّرْس: ${titleAr}`,
    `Imam Al-Tahawi (239–321 AH):\n\nFrom Al-Aqeedah Al-Tahawiyyah for Lesson ${n}:\n\n'What missed the servant could never have hit him — and what hit him could never have missed him.'\n\nAl-Tahawiyyah: A text accepted by all of Ahl al-Sunnah — gathering their consensus.\n\nLesson topic: ${title}`,
    `الطَّحَاوِيُّ جَمَعَ عَقِيدَةَ الإِمَامِ أَحْمَد وَأَبِي حَنِيفَة فِي مَتْن صَغِير بَلَغَ ٢٩٩ نُقْطَة. هَذَا الدَّرْسُ يُكَمِّلُ فَهْمَنَا لِعَقِيدَةِ أَهْلِ السُّنَّة.`,
    [{arabic:"طَحَاوِيَّة",transliteration:"ṭaḥāwiyyah",english:"Al-Tahawiyyah text (Imam al-Tahawi's creed)",pos:"proper noun"},
     {arabic:"يَقِين",transliteration:"yaqīn",english:"certainty/conviction",pos:"noun (m)"},
     {arabic:"بَعْث",transliteration:"baʿth",english:"resurrection",pos:"noun (m)"},
     {arabic:"حَشْر",transliteration:"ḥashr",english:"gathering (on Judgment Day)",pos:"noun (m)"},
     {arabic:"صِرَاط",transliteration:"ṣirāṭ",english:"bridge (over Hellfire)",pos:"noun (m)"}],
    "Al-Tahawi's Method — Consensus of Ahl al-Sunnah","مَنْهَجُ الطَّحَاوِيِّ — إِجْمَاعُ أَهْلِ السُّنَّة",
    `Imam al-Tahawi wrote: 'This is the detailed account of the beliefs of Ahl al-Sunnah wa-l-Jama'ah.'\n\nHis text was accepted across madhhabs because:\n1. Based on clear Quran and Sunnah\n2. Avoids extreme positions\n3. Reflects pre-Mutazilite consensus\n\nLesson ${n} focuses on: ${title}`,
    {arabic:"«وَنُحِبُّ أَهْلَ العَدْلِ وَالأَمَانَةِ وَنُبْغِضُ أَهْلَ الجَوْرِ وَالخِيَانَة»",translation:"'We love the people of justice and trustworthiness, and we dislike the people of injustice and treachery.' — Al-Tahawi's words on character"},
    {q:`Al-Aqeedah Al-Tahawiyyah was written by:`,opts:["Ibn Taymiyyah","Imam al-Nawawi","Imam Abu Ja'far al-Tahawi (239-321 AH)","Imam al-Ghazali"],a:2},
    {q:`The statement 'What missed the servant could never have hit him' relates to:`,opts:["Archery practice","Qadar — divine decree: everything that happens was decreed, everything that didn't was also decreed not to happen","Angels' actions","The scale on Judgment Day"],a:1});
}),

// ─── AQEEDAH FOR BEGINNERS — Lessons 1–14 ─────────────────────────────────

mk("aqeedah-beginners",1,"What is Aqeedah and Why Does It Matter?","مَا هِيَ العَقِيدَةُ وَلِمَاذَا تُهِمّ؟",
"Introduction to Islamic creed — what Muslims believe and why it forms the foundation of everything.",
"العَقِيدَةُ الإِسْلَامِيَّة:\n\nمَا يُؤْمِنُ بِهِ المُسْلِم:\n• اللهُ وَحْدَهُ — خَالِقٌ وَاحِدٌ — رَبٌّ وَاحِد — مَعْبُودٌ وَاحِد\n• مَلَائِكَتُهُ — رُسُلُهُ — كُتُبُهُ — اليَوْمُ الآخِر — القَدَر\n\nلِمَاذَا هِيَ الأَوَّل؟\n• المَنْزِلُ يَحْتَاجُ أَسَاسًا — الجِسْمُ يَحْتَاجُ قَلْبًا — العِبَادَةُ تَحْتَاجُ عَقِيدَة\n• ﴿فَاعْلَمْ أَنَّهُ لَا إِلَهَ إِلَّا اللهُ﴾ [محمد: ١٩] — العِلْمُ قَبْلَ العَمَل\n\nأَوَّلُ مَا نَزَلَ: اقْرَأْ — اقْرَأْ — اقْرَأ (قَبْلَ الصَّلَاة وَالزَّكَاة)",
"Islamic Creed:\n\nWhat Muslims believe:\n• Allah alone — one Creator — one Lord — one Deity\n• His Angels — His Messengers — His Books — Last Day — Divine Decree\n\nWhy is it first?\n• A house needs a foundation — a body needs a heart — worship needs creed\n• 'Know that there is no god except Allah.' [47:19] — Knowledge before action\n\nFirst Quran revealed: 'Read! Read! Read!' — before prayer and Zakah were obligated",
"الإِيمَانُ كَالشَّجَرَة: الجُذُور (العَقِيدَة) — الجِذْع (العِبَادَات) — الأَغْصَان (الأَخْلَاق). بِدُونِ جُذُور قَوِيَّة لَا تَصْمُدُ الشَّجَرَة.",
[{arabic:"عَقِيدَة",transliteration:"ʿaqīdah",english:"creed/belief",pos:"noun (f)"},
 {arabic:"أَسَاس",transliteration:"asās",english:"foundation/basis",pos:"noun (m)"},
 {arabic:"إِيمَان",transliteration:"īmān",english:"faith/belief",pos:"noun (m)"},
 {arabic:"يَقِين",transliteration:"yaqīn",english:"certainty",pos:"noun (m)"},
 {arabic:"تَوْحِيد",transliteration:"tawḥīd",english:"monotheism/singling out Allah",pos:"noun (m)"}],
"'Know' before 'Do' — Knowledge Precedes Action","«اعْلَمْ» قَبْلَ «اعْمَلْ»",
"Quran 47:19 — 'Know that there is no god except Allah' — uses 'know' (not 'say' or 'do').\n\nThis is the Quranic order:\n1. KNOW → Aqeedah\n2. Then WORSHIP → 'Istighfar' in the same verse\n3. Then ETHICS → Good character\n\nIslam began in Makkah with 13 years of pure aqeedah before fiqh.",
{arabic:"﴿فَاعْلَمْ أَنَّهُ لَا إِلَهَ إِلَّا اللهُ وَاسْتَغْفِرْ لِذَنْبِك﴾",translation:"'Know that there is no god except Allah, and seek forgiveness for your sin.' [47:19] — Knowledge THEN action"},
{q:"Aqeedah is taught first in Islam because:",opts:["It's the easiest topic","It is the foundation of all worship and actions — wrong aqeedah corrupts deeds","It impresses others","It came last in the Quran"],a:1},
{q:"How many years did the Quran focus on aqeedah in Makkah before detailed laws came?",opts:["3 years","5 years","13 years","23 years"],a:2}),

...["The Six Pillars of Iman","Believing in Allah — Tawhid for Beginners",
  "Believing in Angels","Believing in the Books of Allah",
  "Believing in the Prophets and Messengers","Believing in the Last Day",
  "Believing in Qadar (Divine Decree)","The Three Fundamentals — Al-Usul al-Thalatha",
  "What is Tawhid — Simple Explanation","What is Shirk and Its Danger",
  "Signs of Weak and Strong Iman","Maintaining and Strengthening Your Iman",
  "Final Aqeedah Review for Beginners"]
.map((title,i) => {
  const n = i+2;
  const titleArs = ["أَرْكَانُ الإِيمَانِ السِّتَّة","الإِيمَانُ بِاللهِ","الإِيمَانُ بِالمَلَائِكَة",
    "الإِيمَانُ بِكُتُبِ اللهِ","الإِيمَانُ بِالأَنْبِيَاءِ وَالرُّسُل","الإِيمَانُ بِاليَوْمِ الآخِر",
    "الإِيمَانُ بِالقَدَر","الأُصُولُ الثَّلَاثَة","مَا هُوَ التَّوْحِيد",
    "مَا هُوَ الشِّرْكُ وَخَطَرُهُ","عَلَامَاتُ الإِيمَانِ الضَّعِيفِ وَالقَوِيّ","تَقْوِيَةُ الإِيمَان","مُرَاجَعَةٌ شَامِلَة"];
  return mk("aqeedah-beginners",n,title,titleArs[i]||`Pillar ${n}`,`Beginner aqeedah lesson ${n}: ${title}`,
    `الدَّرْسُ ${n}: ${titleArs[i]||title}\n\n«آمَنْتُ بِاللهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ وَاليَوْمِ الآخِرِ وَالقَدَرِ خَيْرِهِ وَشَرِّهِ مِنَ اللهِ تَعَالَى»\n\nهَذَا الدَّرْسُ يُعَلِّمُ بِأُسْلُوبٍ مُبَسَّط وَواضِح لِلمُبْتَدِئِين.`,
    `Lesson ${n}: ${title}\n\n'I believe in Allah, His Angels, His Books, His Messengers, the Last Day, and Qadar — good and bad — from Allah.'\n\nThis lesson teaches with a simple, clear method for beginners.`,
    `الإِيمَانُ يَزِيدُ بِالطَّاعَةِ وَيَنْقُصُ بِالمَعْصِيَة — هَذَا الدَّرْسُ يُقَوِّي إِيمَانَنَا بِالعِلْم.`,
    [{arabic:"رُكْن",transliteration:"rukn",english:"pillar/fundamental",pos:"noun (m)"},
     {arabic:"إِيمَان",transliteration:"īmān",english:"faith/belief",pos:"noun (m)"},
     {arabic:"غَيْب",transliteration:"ghayb",english:"unseen (what only Allah knows)",pos:"noun (m)"},
     {arabic:"يَقِين",transliteration:"yaqīn",english:"certainty",pos:"noun (m)"},
     {arabic:"شُكْر",transliteration:"shukr",english:"gratitude/thankfulness",pos:"noun (m)"}],
    "Building Iman Step by Step","بِنَاءُ الإِيمَانِ خُطْوَةً خُطْوَة",
    `The Quran builds iman through multiple approaches:\n1. Signs in creation (آيات) — seeing Allah through His creation\n2. Stories of prophets — learning from their struggles\n3. Direct commands — acting on belief\n4. Reminders of death and afterlife — maintaining perspective\n\nLesson ${n} uses one of these approaches for: ${title}`,
    {arabic:"«يَزِيدُ الإِيمَانُ بِالطَّاعَةِ وَيَنْقُصُ بِالمَعْصِيَة» — أَهْلُ السُّنَّة",translation:"'Iman increases with obedience and decreases with sin.' — Ahl al-Sunnah's position on Iman"},
    {q:`What are the six pillars of Iman?`,opts:["Prayer, Fasting, Zakah, Hajj, Shahada, Jihad","Believing in Allah, Angels, Books, Prophets, Last Day, and Divine Decree","Tawhid, Sunnah, Quran, Prayer, Fasting, Hajj","Only Allah, Quran, and Muhammad ﷺ"],a:1},
    {q:`How does a Muslim strengthen their Iman?`,opts:["By being born Muslim","Through knowledge, worship, remembrance of Allah, reading Quran, and avoiding sin","Only through Hajj","By memorizing hadith only"],a:1});
}),

];
