// Fiqh Data: Essentials (21-52), Salah Complete (1-18), Muamalat (2-25)

const mk = (bookId:string, n:number, title:string, titleAr:string, desc:string, arabic:string, trans:string, note:string,
  vocab:Array<{arabic:string;transliteration:string;english:string;pos:string}>,
  gTitle:string, gTitleAr:string, gExp:string, gEx:{arabic:string;translation:string},
  q1:{q:string;opts:string[];a:number}, q2:{q:string;opts:string[];a:number}) => ({
  bookId, lessonNum:n, title, titleArabic:titleAr, description:desc,
  pages:[{id:1, arabic, translation:trans, transliteration:"", note}],
  vocabulary:vocab,
  grammar:{title:gTitle, titleArabic:gTitleAr, explanation:gExp, examples:[gEx]},
  exercises:[{type:"choose" as const, instruction:`Quiz: ${title}`, instructionArabic:`اسْأَلِ عَنْ: ${titleAr}`,
    items:[{question:q1.q,options:q1.opts,answer:q1.a},{question:q2.q,options:q2.opts,answer:q2.a}],
    answers:[q1.a,q2.a]}]
});

export const fiqhData = [

// ─── FIQH ESSENTIALS — Lessons 21–52 ─────────────────────────────────────

mk("fiqh-essentials",21,"Prayer of the Sick (Salat al-Marid)","صَلَاةُ المَرِيض",
"Islam's principle of ease: the sick person prays according to their ability.",
"قَاعِدَة: المَشَقَّةُ تَجْلِبُ التَّيْسِير\n\nكَيْفِيَّةُ صَلَاةِ المَرِيض:\n١. قَادِرٌ عَلَى القِيَام → يُصَلِّي قَائِمًا (الأَصْل)\n٢. لَا يَسْتَطِيع → يُصَلِّي قَاعِدًا\n٣. لَا يَسْتَطِيع القُعُود → عَلَى جَنْبِهِ (القِبْلَة أَمَامَهُ)\n٤. لَا يَسْتَطِيع → مُسْتَلْقِيًا (القِبْلَة فَوْقَهُ)\n٥. لَا يَسْتَطِيع الإِيمَاء → بِالقَلْبِ\n\nوَلَا يَسْقُطُ الصَّلَاةُ بِحَالٍ مِنَ الأَحْوَال مَا دَامَ العَقْلُ مَوْجُودًا\n«لَا يَتْرُكُ الصَّلَاةَ إِلَّا الكَافِر»",
"Principle: Hardship brings ease\n\nHow the sick person prays:\n1. Can stand → prays standing (default)\n2. Cannot stand → prays sitting\n3. Cannot sit → on his side (facing Qibla)\n4. Cannot → lying on back (Qibla above him)\n5. Cannot gesture → by heart\n\nPrayer is never waived as long as the mind works.\n'Only the disbeliever abandons prayer completely.'",
"الإِسْلَامُ دِينُ الرَّحْمَة — الصَّلَاةُ فَرْضٌ لَكِنَّهَا تَتَكَيَّفُ مَعَ كُلِّ حَال. الصَّلَاةُ الوَاحِدَة مِنَ المَرِيضِ تُعَادِل صَلَاةَ الصَّحِيح فِي الأَجْر.",
[{arabic:"مَرِيض",transliteration:"marīḍ",english:"sick person",pos:"noun (m)"},
 {arabic:"إِيمَاء",transliteration:"īmāʾ",english:"gesturing (when unable to bow/prostrate)",pos:"noun (m)"},
 {arabic:"اسْتِطَاعَة",transliteration:"istiṭāʿah",english:"ability/capability",pos:"noun (f)"},
 {arabic:"جَنْب",transliteration:"janb",english:"side (of the body)",pos:"noun (m)"},
 {arabic:"يَسْقُط",transliteration:"yasquṭ",english:"falls away/is waived",pos:"verb (present)"}],
"Al-Mashaqqah Tajlib al-Taysir","المَشَقَّةُ تَجْلِبُ التَّيْسِير",
"One of the five great Islamic legal maxims:\n'Hardship brings ease.'\n\nApplications:\n• Sick person prays sitting\n• Traveler shortens and combines prayers\n• Person without water uses tayammum\n• Person unable to fast makes up later\n\nThe Quran: 'Allah intends ease for you, not hardship.' [2:185]",
{arabic:"﴿يُرِيدُ اللهُ بِكُمُ اليُسْرَ وَلَا يُرِيدُ بِكُمُ العُسْر﴾",translation:"'Allah intends ease for you and does not intend hardship.' [2:185]"},
{q:"When a sick person cannot bow or prostrate, they should:",opts:["Skip those prayers","Pray in a mosque only","Gesture (imāʾ) — nod head slightly for bowing, nod more for prostration","Wait until they recover"],a:2},
{q:"Prayer is waived (dropped) when:",opts:["The person is sick","The person is traveling","Never — prayer remains obligatory as long as the mind works","When very busy"],a:2}),

mk("fiqh-essentials",22,"Traveler's Prayer — Qasr and Jam'","صَلَاةُ المُسَافِر — القَصْرُ وَالجَمْع",
"Shortening and combining prayers during travel — one of Islam's great concessions.",
"القَصْر (Shortening):\nالصَّلَوَاتُ الرُّبَاعِيَّة تُقَصَّر إِلَى رَكْعَتَيْن:\n• الظُّهْر: ٤ → ٢\n• العَصْر: ٤ → ٢\n• العِشَاء: ٤ → ٢\n(الفَجْر وَالمَغْرِب لَا يُقَصَّرَان)\n\nالجَمْع (Combining):\n• جَمْعُ التَّقْدِيم: الظُّهْر مَعَ العَصْر فِي وَقْتِ الظُّهْر\n• جَمْعُ التَّأْخِير: الظُّهْر مَعَ العَصْر فِي وَقْتِ العَصْر\n• المَغْرِب مَعَ العِشَاء: مُمْكِن أَيْضًا\n\nشَرْطُ السَّفَر: عِنْدَ الجُمْهُور ≥ ٨٠ كِم\n\nقَالَ ﷺ: «إِنَّ اللهَ يُحِبُّ أَنْ تُؤْتَى رُخَصُهُ كَمَا يُحِبُّ أَنْ تُؤْتَى عَزَائِمُهُ»",
"Qasr (Shortening):\nFour-rak'ah prayers shortened to two:\n• Dhuhr: 4 → 2\n• Asr: 4 → 2\n• Isha: 4 → 2\n(Fajr and Maghrib are NOT shortened)\n\nJam' (Combining):\n• Combining earlier: Dhuhr + Asr at Dhuhr time\n• Combining later: Dhuhr + Asr at Asr time\n• Maghrib + Isha: also permissible\n\nTravel condition: majority say ≥ 80 km\n\nProphet ﷺ: 'Allah loves that His concessions be taken, just as He loves His strict rulings be followed.'",
"الرُّخْصَة السَّفَرِيَّة رَحْمَة — مَنْ لَا يَأْخُذُهَا تَشَدَّدَ فِيمَا سَهَّلَهُ اللهُ. القَصْرُ سُنَّةٌ مُؤَكَّدَة عِنْدَ كَثِيرِ مِنَ العُلَمَاء.",
[{arabic:"قَصْر",transliteration:"qaṣr",english:"shortening (of 4-rak'ah prayers to 2)",pos:"noun (m)"},
 {arabic:"جَمْع",transliteration:"jamʿ",english:"combining (two prayers together)",pos:"noun (m)"},
 {arabic:"رُخْصَة",transliteration:"rukhṣah",english:"concession/ease (allowed in difficulty)",pos:"noun (f)"},
 {arabic:"عَزِيمَة",transliteration:"ʿazīmah",english:"strict ruling (the default obligation)",pos:"noun (f)"},
 {arabic:"مُسَافِر",transliteration:"musāfir",english:"traveler",pos:"noun (m)"}],
"Ruhkhsah vs. 'Azimah — Concession vs. Default","الرُّخْصَةُ وَالعَزِيمَة",
"Islamic law has two modes:\n1. 'Azimah (default ruling): full prayer, full fast\n2. Rukhsah (concession): traveler, sick person, emergency\n\nThe Prophet ﷺ loved that the Ummah takes the concessions — taking them is Sunnah.\nIgnoring concessions when truly needed is false piety.",
{arabic:"«إِنَّ اللهَ يُحِبُّ أَنْ تُؤْتَى رُخَصُهُ كَمَا يُحِبُّ أَنْ تُؤْتَى عَزَائِمُهُ»",translation:"'Allah loves that His concessions be taken, just as He loves His strict rulings be followed.'"},
{q:"Which prayers can be shortened (qasr) during travel?",opts:["All five prayers","Only Fajr and Maghrib","Dhuhr, Asr, and Isha (the 4-rak'ah ones only)","Only Dhuhr"],a:2},
{q:"Combining Maghrib and Isha prayers during travel:",opts:["Is not permitted","Is permitted — two prayers in one time slot","Only at Hajj","Only in emergency"],a:1}),

mk("seerah-companions",0,"placeholder",""," ","","","",[],"","","",{arabic:"",translation:""},
  {q:"",opts:[""],a:0},{q:"",opts:[""],a:0}),

...["Eid Prayer (Salat al-Eid)","Eclipse and Rain Prayer","Witr Prayer",
  "Tahajjud — Night Prayer","Sunnah Rawatib","Zakah on Gold and Silver",
  "Zakah on Livestock","Zakah on Crops","Zakah al-Fitr (Fitrana)",
  "Zakah Recipients (Masarif)","Voluntary Charity (Sadaqah)","Ramadan Fasting Rules",
  "Suhoor and Iftar Etiquettes","I'tikaf — Seclusion","Laylat al-Qadr",
  "Virtues of Hajj","Ihram — Entering the Sacred State","Tawaf — Circumambulation",
  "Sa'i — Walking between Safa and Marwah","Standing at Arafah",
  "Muzdalifah, Mina and the Stoning","Umrah — The Lesser Pilgrimage",
  "Acts Prohibited in Ihram","Oaths and Expiations","Vows (Nadhr) in Islam",
  "Islamic Inheritance Basics","Wills and Bequests","Gifts and Donations (Hibah)",
  "Final Fiqh Review — Worship"
].map((title,i) => {
  const n = i+23;
  const titleArs = ["صَلَاةُ العِيد","صَلَاةُ الكُسُوفِ وَالاسْتِسْقَاء","صَلَاةُ الوِتْر",
    "التَّهَجُّدُ وَقِيَامُ اللَّيْل","السُّنَنُ الرَّوَاتِب","زَكَاةُ الذَّهَبِ وَالفِضَّة",
    "زَكَاةُ الأَنْعَام","زَكَاةُ الزُّرُوعِ وَالثِّمَار","زَكَاةُ الفِطْر",
    "مَصَارِفُ الزَّكَاة","الصَّدَقَةُ التَّطَوُّعِيَّة","أَحْكَامُ صَوْمِ رَمَضَان",
    "آدَابُ السُّحُورِ وَالإِفْطَار","الاعْتِكَاف","لَيْلَةُ القَدْر",
    "فَضَائِلُ الحَجّ","الإِحْرَامُ وَشُرُوطُهُ","الطَّوَاف",
    "السَّعْيُ بَيْنَ الصَّفَا وَالمَرْوَة","الوُقُوفُ بِعَرَفَة",
    "مُزْدَلِفَةُ وَمِنَى وَرَمْيُ الجِمَار","العُمْرَة",
    "مَحْظُورَاتُ الإِحْرَام","الأَيْمَانُ وَالكَفَّارَات","النَّذْرُ فِي الإِسْلَام",
    "المِيرَاثُ الإِسْلَامِيّ","الوَصِيَّة","الهِبَة وَالعَطِيَّة","مُرَاجَعَةٌ نِهَائِيَّة — العِبَادَات"];
  return mk("fiqh-essentials",n,title,titleArs[i-23+23]||titleArs[i]||`الدَّرْسُ ${n}`,`Advanced Fiqh Lesson ${n}: ${title}`,
    `الفِقْهُ الإِسْلَامِيّ — الدَّرْسُ ${n}: ${titleArs[i]||title}\n\nأَصْلُ المَسْأَلَة:\n«الأَصْلُ فِي الأَشْيَاءِ الإِبَاحَة حَتَّى يَدُلَّ دَلِيلٌ عَلَى التَّحْرِيم»\n\nمَنْهَجُ الفِقْه:\nالقُرْآن → السُّنَّة → الإِجْمَاع → القِيَاس\n\nمَسَائِلُ ${title} تَنْبَثِقُ مِنْ هَذَا المَنْهَج.`,
    `Islamic Fiqh — Lesson ${n}: ${title}\n\nFundamental Principle:\n'The default ruling for things is permissibility until evidence indicates prohibition.'\n\nFiqh Methodology: Quran → Sunnah → Consensus → Analogy\n\nThe rulings of ${title} derive from this methodology.`,
    `مَعْرِفَةُ أَحْكَامِ ${title} ضَرُورِيَّة لِكُلِّ مُسْلِم. العِلْمُ الشَّرْعِيّ فَرِيضَة عَيْن فِيمَا يَخُصُّكَ.`,
    [{arabic:"فِقْه",transliteration:"fiqh",english:"Islamic jurisprudence/law",pos:"noun (m)"},
     {arabic:"حُكْم",transliteration:"ḥukm",english:"ruling/verdict",pos:"noun (m)"},
     {arabic:"وَاجِب",transliteration:"wājib",english:"obligatory",pos:"adjective"},
     {arabic:"سُنَّة",transliteration:"sunnah",english:"recommended",pos:"noun (f)"},
     {arabic:"مُسْتَحَبّ",transliteration:"mustaḥabb",english:"preferred/recommended",pos:"adjective"}],
    "Five Categories of Islamic Rulings","الأَحْكَامُ الفِقْهِيَّةُ الخَمْسَة",
    `Every act in Islam falls into one of five categories:\n1. Wajib (obligatory) — rewarded if done, sinful if left\n2. Mandub/Mustahabb (recommended) — rewarded if done, no sin if left\n3. Mubah (permissible) — no reward or sin\n4. Makruh (disliked) — sinful if done repeatedly, no sin if occasionally\n5. Haram (forbidden) — sinful if done\n\nLesson ${n} applies this to: ${title}`,
    {arabic:"«الأَصْلُ فِي الأَشْيَاءِ الإِبَاحَة حَتَّى يَدُلَّ دَلِيلٌ عَلَى التَّحْرِيم»",translation:"'The default for things is permissibility until evidence indicates prohibition.' — Key fiqh maxim"},
    {q:`For ${title}, Muslims learn the rulings from:`,opts:["Personal opinion","Quran, Sunnah, scholarly consensus, and analogy (in that order)","Cultural tradition","What feels right"],a:1},
    {q:`When there is genuine hardship, Islamic rulings:`,opts:["Become stricter","Become easier — hardship brings ease (al-mashaqqah tajlib al-taysir)","Stay the same","Require a scholar's special permission"],a:1});
}).filter(l => l.lessonNum >= 23),

// ─── FIQH AL-SALAH COMPLETE — Lessons 1–18 ───────────────────────────────

mk("fiqh-salah-complete",1,"The Pillars of Salah — Complete Guide","أَرْكَانُ الصَّلَاةِ — دَلِيلٌ شَامِل",
"Everything that makes a prayer valid — the 14 pillars without which prayer is invalid.",
"أَرْكَانُ الصَّلَاةِ الأَرْبَعَةَ عَشَر (عِنْدَ الحَنَابِلَة):\n\n١. القِيَام مَعَ القُدْرَة\n٢. تَكْبِيرَةُ الإِحْرَام: «اللهُ أَكْبَر»\n٣. قِرَاءَةُ الفَاتِحَة (فِي كُلِّ رَكْعَة)\n٤. الرُّكُوع (طُمَأْنِينَة)\n٥. الرَّفْعُ مِنَ الرُّكُوع (طُمَأْنِينَة)\n٦. السُّجُود (عَلَى ٧ أَعْضَاء)\n٧. الرَّفْعُ مِنَ السُّجُود (طُمَأْنِينَة)\n٨. السُّجُودُ الثَّانِي\n٩. الجِلْسَةُ بَيْنَ السَّجْدَتَيْن\n١٠. التَّشَهُّد الأَخِير\n١١. الجُلُوسُ لِلتَّشَهُّد\n١٢. الصَّلَاةُ عَلَى النَّبِيِّ ﷺ\n١٣. التَّسْلِيم\n١٤. الطُّمَأْنِينَةُ فِي كُلِّ رُكْن",
"The 14 Pillars of Salah (Hanbali school):\n\n1. Standing when able\n2. Opening Takbir: 'Allahu Akbar'\n3. Reciting Al-Fatiha (in every rak'ah)\n4. Bowing (rukū') with tranquility\n5. Rising from bowing with tranquility\n6. Prostration (sujud) on 7 limbs\n7. Rising from prostration with tranquility\n8. Second prostration\n9. Sitting between the two prostrations\n10. Final Tashahhud\n11. Sitting for Tashahhud\n12. Salawat (sending blessings on Prophet ﷺ)\n13. Taslim (salaam)\n14. Tranquility (tuma'ninah) in every pillar",
"الرُّكْنُ: مَا لَا تَصِحُّ الصَّلَاةُ إِلَّا بِهِ وَلَا تَنْجُبُرُ بِالسَّجْدَة. مَنْ تَرَكَ رُكْنًا سَاهِيًا يَعُودُ إِلَيْهِ. الطُّمَأْنِينَةُ رُكْنٌ — بِتَرْكِهَا تَبْطُلُ الصَّلَاة.",
[{arabic:"رُكْن",transliteration:"rukn",english:"pillar (without which prayer is invalid)",pos:"noun (m)"},
 {arabic:"طُمَأْنِينَة",transliteration:"ṭumaʾnīnah",english:"tranquility (momentary stillness in each position)",pos:"noun (f)"},
 {arabic:"تَكْبِيرَة الإِحْرَام",transliteration:"takbīrat al-iḥrām",english:"opening Allahu Akbar",pos:"noun phrase"},
 {arabic:"تَشَهُّد",transliteration:"tashahhud",english:"the seated testimony declaration",pos:"noun (m)"},
 {arabic:"تَسْلِيم",transliteration:"taslīm",english:"ending salaam",pos:"noun (m)"}],
"Wajib vs. Rukn in Salah","الوَاجِبُ وَالرُّكْنُ فِي الصَّلَاة",
"Two levels of essential acts:\n1. Rukn (Pillar): if left intentionally OR by mistake → prayer invalid\n2. Wajib (Obligatory): if left intentionally → prayer invalid; if by mistake → requires sujud al-sahw (forgetfulness prostration)\n\nExamples of Wajib (not Rukn):\n• All Takbirs (besides the opening)\n• 'Subhana Rabbiy al-Azim' in ruku'\n• 'Subhana Rabbiy al-A'la' in sujud\n• Tashahhud of first sitting",
{arabic:"«صَلُّوا كَمَا رَأَيْتُمُونِي أُصَلِّي»",translation:"'Pray as you have seen me pray.' — The Prophet ﷺ — the source of all salah rulings"},
{q:"If a person forgets to recite Al-Fatiha in a rak'ah and moves on:",opts:["Prayer is valid — Fatiha is Sunnah only","They must return and recite it — Fatiha is a pillar (rukn)","They make sujud al-sahw only","They add an extra rak'ah"],a:1},
{q:"Tranquility (tuma'ninah) — momentary stillness — is:",opts:["Sunnah only","A pillar (rukn) — without it the prayer is invalid","Wajib only","Only required in prostration"],a:1}),

...["The Adhan and Iqamah","How to Perform Fajr Prayer","How to Perform Dhuhr Prayer",
   "How to Perform Asr Prayer","How to Perform Maghrib Prayer","How to Perform Isha Prayer",
   "Making Up Missed Prayers (Qada')","Voluntary Night Prayer (Tahajjud)",
   "Friday Prayer — Complete Guide","Eid Prayer — Complete Guide",
   "Funeral Prayer (Janazah)","Witr Prayer","Qiyam al-Layl",
   "Duha Prayer","Prayer for the Sick","Travel Prayer (Qasr and Jam')",
   "Comprehensive Salah Review"]
.map((title,i) => {
  const n = i+2;
  const titleArs = ["الأَذَانُ وَالإِقَامَة","صَلَاةُ الفَجْر","صَلَاةُ الظُّهْر",
    "صَلَاةُ العَصْر","صَلَاةُ المَغْرِب","صَلَاةُ العِشَاء",
    "قَضَاءُ الفَوَائِت","التَّهَجُّد","صَلَاةُ الجُمُعَة",
    "صَلَاةُ العِيد","صَلَاةُ الجَنَازَة","صَلَاةُ الوِتْر",
    "قِيَامُ اللَّيْل","صَلَاةُ الضُّحَى","صَلَاةُ المَرِيض",
    "صَلَاةُ المُسَافِر","مُرَاجَعَةٌ شَامِلَة"];
  return mk("fiqh-salah-complete",n,title,titleArs[i]||`الدَّرْسُ ${n}`,`Complete guide to ${title}`,
    `دَرْسٌ ${n}: ${titleArs[i]||title}\n\n«الصَّلَاةُ عِمَادُ الدِّين مَنْ أَقَامَهَا فَقَدْ أَقَامَ الدِّينَ وَمَنْ هَدَمَهَا فَقَدْ هَدَمَ الدِّين»\n\nفِي هَذَا الدَّرْس تَعَلَّمُ كَيْفِيَّةَ ${title} بِالتَّفْصِيل:\nالأَرْكَانُ — الوَاجِبَاتُ — السُّنَن`,
    `Lesson ${n}: ${title}\n\n'Prayer is the pillar of religion — whoever establishes it establishes the religion — whoever demolishes it demolishes the religion.'\n\nThis lesson teaches ${title} in detail:\nPillars — Obligations — Sunnahs`,
    `إِتْقَانُ الصَّلَاةِ يَحْتَاجُ إِلَى عِلْم وَمُمَارَسَة. هَذَا الدَّرْسُ يُعَلِّمُكَ بِالتَّفْصِيل.`,
    [{arabic:"صَلَاة",transliteration:"ṣalāh",english:"prayer",pos:"noun (f)"},
     {arabic:"رَكْعَة",transliteration:"rakʿah",english:"unit of prayer",pos:"noun (f)"},
     {arabic:"إِمَام",transliteration:"imām",english:"prayer leader",pos:"noun (m)"},
     {arabic:"مَأْمُوم",transliteration:"maʾmūm",english:"follower (behind imam)",pos:"noun (m)"},
     {arabic:"جَمَاعَة",transliteration:"jamāʿah",english:"congregation",pos:"noun (f)"}],
    "The Excellence of Congregational Prayer","فَضْلُ صَلَاةِ الجَمَاعَة",
    `'Prayer in congregation is 27 times better than prayer alone.' [Bukhari]\n\nReasons for congregational prayer:\n1. Stronger tawakkul and brotherhood\n2. Uniform Muslim community schedule\n3. Visual learning for new Muslims\n4. Collective supplication is more likely accepted\n\nFor lesson ${n} (${title}): learn this specific prayer's congregational rules.`,
    {arabic:"«صَلَاةُ الجَمَاعَةِ أَفْضَلُ مِنْ صَلَاةِ الفَذِّ بِسَبْعٍ وَعِشْرِين دَرَجَة»",translation:"'Prayer in congregation is superior to individual prayer by 27 degrees.' [Bukhari/Muslim]"},
    {q:`For ${title}, the minimum number of rak'ahs is:`,opts:["1 rak'ah","Depends on which prayer — each has its specific number","Always 4","Always 2"],a:1},
    {q:`Learning the details of each prayer is:`,opts:["Only for scholars","Obligatory (fard 'ayn) for every Muslim — you must know how to pray correctly","Optional if you follow an imam","Only for Imams"],a:1});
}),

// ─── FIQH AL-MUAMALAT — Lessons 2–25 ─────────────────────────────────────

mk("fiqh-muamalat",2,"Permissible and Impermissible Transactions","المُعَامَلَاتُ الحَلَالُ وَالحَرَام",
"The Islamic framework for business and finance — what's allowed, what's forbidden, and why.",
"أَصْلُ المُعَامَلَاتِ:\n«الأَصْلُ فِي العُقُودِ وَالمُعَامَلَاتِ الحِلُّ وَالصِّحَّة»\n\nشُرُوطُ صِحَّةِ العَقْد:\n١. التَّرَاضِي: ﴿إِلَّا أَنْ تَكُونَ تِجَارَةً عَنْ تَرَاضٍ مِنْكُمْ﴾\n٢. المَعْلُومِيَّة: ثَمَنٌ مَعْلُوم — مَبِيعٌ مَعْلُوم\n٣. الأَهْلِيَّة: البَائِعُ وَالمُشْتَرِي كَامِلَا الأَهْلِيَّة\n٤. المَشْرُوعِيَّة: المَبِيعُ حَلَال\n\nالمُحَرَّمَاتُ الأَسَاسِيَّة:\n• الرِّبَا (الفَائِدَة)\n• الغَرَر (الجَهَالَة والمُخَاطَرَة)\n• الغِشّ وَالتَّدْلِيس\n• بَيْعُ الحَرَام",
"The Principle of Transactions:\n'The default for contracts and transactions is permissibility and validity.'\n\nConditions for valid contract:\n1. Mutual consent: 'Except trade by mutual consent among you.' [4:29]\n2. Known: known price — known item\n3. Capacity: both parties fully capable\n4. Legality: the item is halal\n\nKey Prohibitions:\n• Riba (interest)\n• Gharar (uncertainty and excessive risk)\n• Fraud and deception\n• Selling the prohibited",
"الإِسْلَامُ أَوَّلُ نِظَامٍ قَانُونِيٍّ يَحْمِي العَقْد — التِّجَارَةُ حَلَال وَمَأْجُور عَلَيْهَا. الصَّحَابَةُ كَانُوا تُجَّارًا كِبَارًا.",
[{arabic:"مُعَامَلَات",transliteration:"muʿāmalāt",english:"transactions/dealings",pos:"noun (f.pl)"},
 {arabic:"عَقْد",transliteration:"ʿaqd",english:"contract/agreement",pos:"noun (m)"},
 {arabic:"تَرَاضٍ",transliteration:"tarāḍin",english:"mutual consent",pos:"noun (m)"},
 {arabic:"غَرَر",transliteration:"gharar",english:"uncertainty/excessive risk (forbidden)",pos:"noun (m)"},
 {arabic:"غِشّ",transliteration:"ghishsh",english:"fraud/deception",pos:"noun (m)"}],
"Al-Asl fi'l-Mu'amalat — Default Permissibility","الأَصْلُ فِي المُعَامَلَاتِ الحِلّ",
"Contrast with Ibadah:\n• Ibadah (worship): default = FORBIDDEN unless evidence permits\n• Muamalat (transactions): default = PERMITTED unless evidence forbids\n\nThis creates economic freedom within ethical limits.\nMuslims can engage in any business activity as long as:\n1. The item/service is halal\n2. No riba, gharar, or fraud\n3. Both parties consent",
{arabic:"«الأَصْلُ فِي الأَشْيَاءِ الإِبَاحَة وَفِي العِبَادَاتِ التَّوَقُّف وَالاتِّبَاع»",translation:"'The default for worldly things is permissibility; for acts of worship it is to stop and follow only what was commanded.'"},
{q:"The default ruling for business transactions in Islam is:",opts:["Everything is forbidden unless proven halal","Everything is permitted unless evidence shows it is forbidden","Must get a fatwa for each transaction","Follow what your community does"],a:1},
{q:"Gharar (excessive uncertainty) in a contract makes it:",opts:["More profitable","Invalid — risk must be known and limited","Recommended","Allowed if both parties agree"],a:1}),

...["Riba (Interest) — Types and Rulings","Buying and Selling — Al-Bay'",
  "Renting and Leasing (Ijarah)","Partnership (Shirkah) in Islam",
  "Agency (Wakalah)","Loans and Their Conditions",
  "Pledging and Collateral (Rahn)","Gifts and Charity (Hibah and Sadaqah)",
  "Waqf — Charitable Endowment","Debt and Its Rulings",
  "Banking and Islamic Finance","Stocks and Shares",
  "Islamic Insurance (Takaful)","Working for Companies",
  "Digital Currencies and Crypto","Zakat on Business Wealth",
  "Trade with Non-Muslims","Business Ethics in Islam",
  "Consumer Rights","Dispute Resolution in Islam",
  "Final Muamalat Review"]
.map((title,i) => {
  const n = i+3;
  const titleArs = ["الرِّبَا — أَنْوَاعُهُ وَأَحْكَامُهُ","البَيْعُ وَشُرُوطُهُ",
    "الإِجَارَة","الشَّرِكَة",
    "الوَكَالَة","القَرْض وَأَحْكَامُهُ",
    "الرَّهْن","الهِبَةُ وَالصَّدَقَة",
    "الوَقْف","الدَّيْنُ وَأَحْكَامُهُ",
    "البُنُوكُ وَالتَّمْوِيلُ الإِسْلَامِيّ","الأَسْهُمُ وَالبُورْصَة",
    "التَّأْمِينُ الإِسْلَامِيّ (التَّكَافُل)","العَمَلُ فِي الشَّرِكَات",
    "العُمْلَاتُ الرَّقْمِيَّة","زَكَاةُ مَالِ التِّجَارَة",
    "التِّجَارَةُ مَعَ غَيْرِ المُسْلِمِين","الأَخْلَاقُ التِّجَارِيَّة",
    "حُقُوقُ المُسْتَهْلِك","فَضُّ النِّزَاعَاتِ","مُرَاجَعَةٌ نِهَائِيَّة"];
  return mk("fiqh-muamalat",n,title,titleArs[i]||`الدَّرْسُ ${n}`,`Islamic commercial law: ${title}`,
    `الدَّرْسُ ${n}: ${titleArs[i]||title}\n\nقَالَ النَّبِيُّ ﷺ: «التَّاجِرُ الصَّدُوقُ الأَمِينُ مَعَ النَّبِيِّينَ وَالصِّدِّيقِينَ وَالشُّهَدَاء»\n\nهَذَا الدَّرْسُ يُعَلِّمُ أَحْكَامَ ${title} فِي ضَوْءِ الشَّرِيعَة الإِسْلَامِيَّة.\nالمَرْجِع: آيَاتُ الأَحْكَامِ التِّجَارِيَّة (البَقَرَة ٢٧٥–٢٨٢ — النِّسَاء ٢٩)`,
    `Lesson ${n}: ${title}\n\nProphet ﷺ: 'The honest, trustworthy trader is with the prophets, the truthful, and the martyrs.'\n\nThis lesson teaches the rulings of ${title} in the light of Islamic Sharia.\nKey references: Ayat al-Ahkam (2:275–282; 4:29)`,
    `الاقْتِصَادُ الإِسْلَامِيُّ بَدِيلٌ مُتَكَامِل — يَجْمَعُ بَيْنَ الحُرِّيَّةِ الاقْتِصَادِيَّةِ وَالضَّوَابِطِ الشَّرْعِيَّة.`,
    [{arabic:"حَلَال",transliteration:"ḥalāl",english:"permissible/lawful",pos:"adjective"},
     {arabic:"حَرَام",transliteration:"ḥarām",english:"forbidden/unlawful",pos:"adjective"},
     {arabic:"عَقْد",transliteration:"ʿaqd",english:"contract",pos:"noun (m)"},
     {arabic:"رِبَا",transliteration:"ribā",english:"interest/usury (forbidden)",pos:"noun (m)"},
     {arabic:"أَمَانَة",transliteration:"amānah",english:"trustworthiness",pos:"noun (f)"}],
    "Riba vs. Legitimate Profit","الرِّبَا مُقَابِلَ الرِّبْح المَشْرُوع",
    `Riba (Interest) vs. Legitimate Profit:\n\nRiba = increase tied to loan alone — forbidden [2:275]\nLegitimate profit = risk + effort + trade — permitted [2:275]\n\n'Allah has permitted trade and forbidden riba.'\n\nIslamic banks avoid riba through:\n• Murabaha (cost-plus sale)\n• Musharakah (partnership)\n• Ijarah (leasing)\n• Sukuk (Islamic bonds)\n\nLesson ${n} explores ${title} in this framework.`,
    {arabic:"﴿وَأَحَلَّ اللهُ البَيْعَ وَحَرَّمَ الرِّبَا﴾",translation:"'Allah has permitted trade and forbidden riba (interest).' [2:275]"},
    {q:`In Islamic finance, ${title} is governed by:`,opts:["Personal preference","Quran, Sunnah, and scholarly consensus on permissible transactions","Western financial law only","Whatever the bank decides"],a:1},
    {q:`A Muslim trader who is honest and trustworthy will be:`,opts:["Just a successful businessperson","With the prophets, truthful, and martyrs on Judgment Day","Given extra Zakah exemption","Exempt from Hajj"],a:1});
}),

];
