// Seerah Data — 3 books: Prophet ﷺ (lessons 4-40), Companions (3-30), Islamic History (2-25)
// Lessons 1-3 of Prophet ﷺ and lessons 1-2 of Companions already exist in arabic-lessons.ts

const mk = (bookId:string, lessonNum:number, title:string, titleArabic:string, description:string,
  arabic:string, translation:string, note:string,
  vocab:Array<{arabic:string;transliteration:string;english:string;pos:string}>,
  grammar:{title:string;titleArabic:string;explanation:string;example:{arabic:string;translation:string}},
  q1:{q:string;opts:string[];a:number}, q2:{q:string;opts:string[];a:number}) => ({
  bookId, lessonNum, title, titleArabic, description,
  pages:[{id:1, arabic, translation, transliteration:"", note}],
  vocabulary: vocab,
  grammar:{title:grammar.title, titleArabic:grammar.titleArabic, explanation:grammar.explanation, examples:[grammar.example]},
  exercises:[{type:"choose" as const, instruction:`Quiz: ${title}`, instructionArabic:`اسْأَلِ عَنْ: ${titleArabic}`,
    items:[{question:q1.q,options:q1.opts,answer:q1.a},{question:q2.q,options:q2.opts,answer:q2.a}],
    answers:[q1.a, q2.a]}]
});

export const seerahData = [

// ── SEERAH PROPHET MUHAMMAD ﷺ — Lessons 4–40 ──────────────────────────────

mk("seerah-prophet-muhammad",4,"Persecution in Makkah","الاضْطِهَادُ فِي مَكَّة","The early Muslims' suffering at the hands of Quraysh — the first martyrs of Islam.",
"الصَّحَابَةُ الأَوَّلُون تَحْتَ التَّعْذِيب:\n• بِلَالٌ رَضِيَ اللهُ عَنْهُ: أُمَيَّةُ بنُ خَلَفٍ يَضَعُهُ تَحْتَ الشَّمْسِ عَلَى الرَّمْلِ الحَارِّ — فَكَانَ يَقُولُ: «أَحَدٌ أَحَدٌ»\n• آلُ يَاسِر: أَوَّلُ شُهَدَاءِ الإِسْلَام — سُمَيَّة تُطْعَنُ بِرُمْح أَبِي جَهْل\n• عَمَّارٌ يُكْرَهُ عَلَى السَّبِّ — فَيَعْتَذِرُ للنَّبِيِّ ﷺ — «كَيْفَ وَجَدْتَ قَلْبَكَ؟» — «مُطْمَئِنًّا بِالإِيمَان» — نَزَلَتْ ﴿إِلَّا مَنْ أُكْرِهَ وَقَلْبُهُ مُطْمَئِنٌّ بِالإِيمَان﴾\n• أَبُو بَكْرٍ يَفْتَدِي بِلَالًا بِثَمَنٍ كَبِير — وَأَبُو جَهْل يَقُول: «لَوْ أَبَيْتَ لَبِعْتُهُ بِأُوقِيَّة»",
"Early companions under torture:\n• Bilal RA: Umayyah ibn Khalaf placed him under the burning sun on hot sand — he said: 'Ahad! Ahad! (One! One!)'\n• The Yasir family: First martyrs of Islam — Sumayyah stabbed with a spear by Abu Jahl\n• Ammar compelled to curse — apologized to Prophet ﷺ — 'How did you find your heart?' — 'At peace with faith' — Quran revealed: 'Except one who is compelled while his heart is firm in faith.'\n• Abu Bakr ransomed Bilal for a high price — Abu Jahl said: 'If you refused, I'd sell him for an ounce of silver'",
"الثَّبَاتُ عَلَى الإِيمَانِ رَغْمَ التَّعْذِيب — العُرُوبَةُ الَّتِي تَحَوَّلَتْ إِلَى إِسْلَام يَغْلِبُ مُلُوك الأَرْض. بِلَالٌ قَالَ «أَحَدٌ» لَا لِيَقُولَهَا بَلْ لأَنَّهَا كُلُّ ما فِي قَلْبِهِ.",
[{arabic:"اضْطِهَاد",transliteration:"iḍṭihād",english:"persecution/oppression",pos:"noun (m)"},
 {arabic:"شَهِيد",transliteration:"shahīd",english:"martyr",pos:"noun (m)"},
 {arabic:"إِكْرَاه",transliteration:"ikrāh",english:"compulsion/coercion",pos:"noun (m)"},
 {arabic:"فِدَاء",transliteration:"fidāʾ",english:"ransom/self-sacrifice",pos:"noun (m)"},
 {arabic:"ثَبَت",transliteration:"thabata",english:"remained firm/steadfast",pos:"verb (past)"}],
{title:"Quran Response to Persecution",titleArabic:"رَدُّ القُرْآنِ عَلَى الاضْطِهَاد",
 explanation:"The Quran responded to every phase of persecution:\n• Torture → 'Does man think he won't be tried?' [29:2]\n• Ikrah → 'Except one compelled...' [16:106]\n• Death → 'And never think of those killed in Allah's cause as dead...' [3:169]\nThe Quran was the companion of the persecuted.",
 example:{arabic:"﴿إِلَّا مَنْ أُكْرِهَ وَقَلْبُهُ مُطْمَئِنٌّ بِالإِيمَان﴾",translation:"'Except one who is compelled while their heart is at rest in faith.' [16:106]"}},
{q:"Who was the first martyr of Islam?",opts:["Bilal RA","Sumayyah RA","Ammar RA","Khabab RA"],a:1},
{q:"What did Bilal say under torture?",opts:["La ilaha illa Allah","Ahad! Ahad! (One! One!)","Allahu Akbar","SubhanAllah"],a:1}),

mk("seerah-prophet-muhammad",5,"The Night Journey & Ascension (Isra & Mi'raj)","الإِسْرَاءُ وَالمِعْرَاج","The miraculous night journey from Makkah to Jerusalem and ascension to the heavens — the gift of five daily prayers.",
"الإِسْرَاء:\n﴿سُبْحَانَ الَّذِي أَسْرَى بِعَبْدِهِ لَيْلًا مِنَ المَسْجِدِ الحَرَامِ إِلَى المَسْجِدِ الأَقْصَى﴾ [الإسراء: ١]\n\nالمِعْرَاج:\n• السَّمَاء الأُولَى: آدَم ﵇\n• الثَّانِيَة: عِيسَى وَيَحْيَى\n• الثَّالِثَة: يُوسُف ﵇\n• الرَّابِعَة: إِدْرِيس\n• الخَامِسَة: هَارُون\n• السَّادِسَة: مُوسَى (يَبْكِي)\n• السَّابِعَة: إِبْرَاهِيم — سِدْرَةُ المُنْتَهَى\n\nفَرْضُ الصَّلَاة: فُرِضَتْ ٥٠ — بِتَخْفِيفِ مُوسَى — حَتَّى ٥\n«هِيَ خَمْسٌ وَهِيَ خَمْسُون»",
"Al-Isra: 'Glory be to He who took His servant on a night journey from the Sacred Mosque to Al-Aqsa Mosque.' [17:1]\n\nAl-Mi'raj through the seven heavens:\n• 1st: Adam ﵇ / 2nd: Jesus & John / 3rd: Joseph / 4th: Idris / 5th: Aaron / 6th: Moses (weeping) / 7th: Ibrahim — Sidrat al-Muntaha\n\nPrescription of Prayer: Initially 50 — through Moses' advice reduced — down to 5.\n'They are five yet they are fifty (in reward).'",
"مُعْجِزَةٌ جَمَعَتْ الزَّمَانَ وَالمَكَان: مَكَّة → القُدْس → السَّمَاوَات فِي لَيْلَة وَاحِدَة. مُوسَى ﵇ بَكَى لِأَنَّ أُمَّةَ مُحَمَّد أَكْثَرُ دُخُولًا لِلْجَنَّةِ مِنْ أُمَّتِهِ.",
[{arabic:"إِسْرَاء",transliteration:"isrāʾ",english:"night journey (Makkah to Jerusalem)",pos:"noun (m)"},
 {arabic:"مِعْرَاج",transliteration:"miʿrāj",english:"ascension (to the heavens)",pos:"noun (m)"},
 {arabic:"سِدْرَة",transliteration:"sidrah",english:"lote tree (at the end of the heavens)",pos:"noun (f)"},
 {arabic:"فُرِضَ",transliteration:"furiḍa",english:"was obligated/prescribed (passive)",pos:"verb (passive past)"},
 {arabic:"مُنْتَهَى",transliteration:"muntahā",english:"ultimate boundary/limit",pos:"noun (m)"}],
{title:"Surah Al-Isra — Context and Purpose",titleArabic:"سُورَةُ الإِسْرَاء — سِيَاقُهَا وَهَدَفُهَا",
 explanation:"Surah 17 (Al-Isra) begins with the night journey and covers the moral code given before it:\n• 17 commandments (like the Ten Commandments) — Islamic ethics for society\n• Confirms the Isra was a reality, not a dream ('Ibdu' = servant, in body and soul)\n• Whoever doubted the Isra left Islam — Abu Bakr believed immediately = Al-Siddiq",
 example:{arabic:"﴿سُبْحَانَ الَّذِي أَسْرَى بِعَبْدِهِ لَيْلًا مِنَ المَسْجِدِ الحَرَامِ إِلَى المَسْجِدِ الأَقْصَى﴾",translation:"'Glory be to He who took His servant on a night journey...' [17:1]"}},
{q:"During Mi'raj, which prophet advised reducing the 50 prayers?",opts:["Ibrahim ﵇","Isa ﵇","Musa ﵇","Adam ﵇"],a:2},
{q:"Where did the Isra (night journey) begin and end?",opts:["Jerusalem to heavens","Makkah to Jerusalem (then Mi'raj to heavens)","Madinah to Makkah","Ta'if to Jerusalem"],a:1}),

mk("seerah-prophet-muhammad",6,"The Hijrah — Migration to Madinah","الهِجْرَةُ إِلَى المَدِينَة","The Prophet's migration to Madinah — the pivotal event that becomes Year 1 of the Islamic calendar.",
"لَيْلَةُ الهِجْرَة (٦٢٢ م):\nقُرَيْش تَقَرَّرُ قَتْلَ النَّبِيِّ ﷺ — «مِنْ كُلِّ قَبِيلَة رَجُل» — وَيُوحَى إِلَيْهِ\nاسْتَبْدَلَهُ عَلِيٌّ فِي فِرَاشِهِ — نَامَ مَكَانَهُ\nخَرَجَ ﷺ بِأَبِي بَكْرٍ → غَارُ ثَوْر (٣ أَيَّام)\nسَمِعَ المُشْرِكُون أَقْدَامَهُم عِنْدَ الغَار — قَالَ أَبُو بَكْر: «يَا رَسُولَ اللهِ لَوْ نَظَرَ أَحَدُهُمْ إِلَى قَدَمَيْهِ لَرَآنَا» — قَالَ ﷺ: «يَا أَبَا بَكْرٍ مَا ظَنُّكَ بِاثْنَيْنِ اللهُ ثَالِثُهُمَا؟»\n﴿إِذْ يَقُولُ لِصَاحِبِهِ لَا تَحْزَنْ إِنَّ اللهَ مَعَنَا﴾ [التوبة: ٤٠]",
"The Night of Hijrah (622 CE):\nQuraysh decided to kill the Prophet ﷺ — 'one man from each tribe' — and was warned by revelation.\nAli ﵁ slept in his bed — stayed in his place.\nLeft with Abu Bakr → Cave of Thawr (3 days)\nThe polytheists' footsteps heard at the cave — Abu Bakr: 'If any of them looks at his feet, he'll see us!' — Prophet ﷺ: 'O Abu Bakr, what do you think of two — when Allah is their third?'\n'When he said to his companion: Do not grieve, indeed Allah is with us.' [9:40]",
"الهِجْرَةُ لَيْسَتْ هَرَبًا — بَلْ هِيَ اسْتِرَاتِيجِيَّة رَبَّانِيَّة: تَرْكُ مَكَّة كَانَ شَرْطًا لِفَتْحِ العَالَم. الهَجَرَةُ مِنَ الشَّرِّ وَاجِبَة — «لَا هِجْرَةَ بَعْدَ الفَتْح» (فِي مَعْنَاهَا الأَصْلِيّ).",
[{arabic:"هِجْرَة",transliteration:"hijrah",english:"migration (for Allah's sake)",pos:"noun (f)"},
 {arabic:"غَار",transliteration:"ghār",english:"cave",pos:"noun (m)"},
 {arabic:"صَاحِب",transliteration:"ṣāḥib",english:"companion (Abu Bakr's title)",pos:"noun (m)"},
 {arabic:"ثَالِث",transliteration:"thālith",english:"third (Allah is their third = with them)",pos:"adjective"},
 {arabic:"أَنْصَار",transliteration:"anṣār",english:"helpers (the Madinah Muslims)",pos:"noun (m.pl)"}],
{title:"'Lā Taḥzan' — Do Not Grieve",titleArabic:"«لَا تَحْزَن» — الطُّمَأْنِينَة فِي اللَّحَظَات الحَرِجَة",
 explanation:"Verse 9:40 — 'Do not grieve, Allah is with us' — captures the Seerah's central lesson:\n• Tawakkul: taking all means (hiding 3 days, secret route) then trusting Allah completely\n• Divine companionship: 'إِنَّ اللهَ مَعَنَا' — not general (with everyone) but special divine aid\n• This verse is the Quran's testimony to Abu Bakr's faithfulness",
 example:{arabic:"﴿لَا تَحْزَنْ إِنَّ اللهَ مَعَنَا﴾",translation:"'Do not grieve — indeed Allah is with us.' [9:40] — The Prophet ﷺ to Abu Bakr in the cave"}},
{q:"Who slept in the Prophet's ﷺ bed on the night of Hijrah?",opts:["Abu Bakr RA","Umar RA","Ali ibn Abi Talib RA","Uthman RA"],a:2},
{q:"The Hijrah marks the start of:",opts:["The Islamic lunar calendar","The Quran's revelation","The Battle of Badr","The building of the Ka'bah"],a:0}),

mk("seerah-prophet-muhammad",7,"Building the Muslim State in Madinah","بِنَاءُ الدَّوْلَةِ الإِسْلَامِيَّة فِي المَدِينَة","The Constitution of Madinah, the first masjid, and brotherhood between Muhajirun and Ansar.",
"أَوَّلُ خُطُوَات البِنَاء:\n\n١. المَسْجِد النَّبَوِيّ: وُضِعَ الأَسَاسُ بِيَدِهِ ﷺ — «اللَّهُمَّ إِنَّهُ لَا خَيْرَ إِلَّا خَيْرُ الآخِرَة» — بَنَى الأَنْصَارُ وَالمُهَاجِرُون سَوِيًّا\n\n٢. المُؤَاخَاة (Brotherhood): أَخَّى بَيْنَ المُهَاجِرِينَ وَالأَنْصَار — عَبْدُ الرَّحْمَنِ بْنُ عَوْفٍ وَسَعْدُ بْنُ الرَّبِيع — «اقْسِمْ مَالِي نِصْفَيْن» — «بَارَكَ اللهُ لَكَ فِي مَالِكَ — دُلَّنِي عَلَى السُّوق»\n\n٣. صَحِيفَةُ المَدِينَة (وَثِيقَة المَدِينَة): أَوَّلُ دُسْتُور فِي التَّارِيخ:\n• المُسْلِمُون أُمَّة وَاحِدَة\n• حِلْفُ مَعَ اليَهُود (شُرُوط)\n• الدِّفَاعُ المُشْتَرَك\n• اللهُ المُحَكِّم فِي النِّزَاعَات",
"First Steps of Building:\n\n1. Masjid al-Nabawi: Foundation laid by his hands ﷺ — 'O Allah there is no good except the Hereafter's good' — Ansar and Muhajirun built together\n\n2. Brotherhood (Mu'akha): Paired Muhajirun and Ansar — Abd al-Rahman ibn Awf and Sa'd ibn al-Rabi' — 'I divide my wealth in half' — 'Allah bless your wealth — just show me the market.'\n\n3. Constitution of Madinah: First written constitution in history:\n• Muslims are one Ummah\n• Alliance with Jewish tribes (conditions)\n• Mutual defense\n• Allah is the arbitrator in disputes",
"أَعْظَمُ تَجْرِبَةٍ اجْتِمَاعِيَّة: رَجُلٌ فَقَدَ كُلَّ شَيْءٍ (المُهَاجِر) + رَجُلٌ يَمْلِكُ كُلَّ شَيْءٍ (الأَنْصَارِيّ) = أُخُوَّة حَقِيقِيَّة. لَمْ يَحْدُثْ مِثْلُهُ فِي التَّارِيخ.",
[{arabic:"مُؤَاخَاة",transliteration:"muʾākhāh",english:"brotherhood bond (between Ansar and Muhajirun)",pos:"noun (f)"},
 {arabic:"مُهَاجِر",transliteration:"muhājir",english:"migrant (from Makkah)",pos:"noun (m)",},
 {arabic:"أَنْصَارِيّ",transliteration:"anṣāriyy",english:"helper (from Madinah)",pos:"noun (m)"},
 {arabic:"صَحِيفَة",transliteration:"ṣaḥīfah",english:"document/constitution",pos:"noun (f)"},
 {arabic:"دُسْتُور",transliteration:"dustūr",english:"constitution/charter",pos:"noun (m)"}],
{title:"The Constitution of Madinah — First Pluralistic State",titleArabic:"وَثِيقَةُ المَدِينَة — أَوَّلُ دُسْتُور تَعَدُّدِيّ",
 explanation:"The Constitution of Madinah (622 CE) established:\n1. Equality under law — Muslim and Jew alike\n2. Religious freedom — each community keeps its laws\n3. Collective defense\n4. Political unity under the Prophet's ﷺ leadership\n\nThis was 1,100 years before the Magna Carta and 1,300 years before Western constitutions.",
 example:{arabic:"«يَثْرِبُ حَرَامٌ جَوْفُهَا لِأَهْلِ هَذِهِ الصَّحِيفَة»",translation:"'The inner part of Madinah is sacred for the people of this document.' — Internal peace guaranteed"}},
{q:"What did Abd al-Rahman ibn Awf ask for when his Ansar brother offered half his wealth?",opts:["He took the wealth","He declined and asked to be shown the market","He asked for land","He returned to Makkah"],a:1},
{q:"The Constitution of Madinah established:",opts:["Only Muslim rights","A pluralistic state with rights for all religious communities and mutual defense","War against all non-Muslims","Monarchy for the Prophet"],a:1}),

mk("seerah-prophet-muhammad",8,"The Battle of Badr","غَزْوَةُ بَدْر","The first major battle of Islam — 313 against 1,000. The miraculous victory that defined the Muslim community.",
"بَدْرٌ الكُبْرَى (رَمَضَان ٢ هـ / ٦٢٤ م):\nالمُسْلِمُون: ٣١٣ — القُرَيْشُ: ١٠٠٠\n\nقَبْلَ المَعْرَكَة:\nالنَّبِيُّ ﷺ يَرْفَعُ يَدَيْهِ: «اللَّهُمَّ إِنَّكَ إِنْ تُهْلِكْ هَذِهِ العِصَابَة لَا تُعْبَدْ فِي الأَرْض» — حَتَّى سَقَطَ رِدَاؤُهُ\nأَبُو بَكْر يُمْسِكُ يَدَهُ: «حَسْبُكَ يَا رَسُولَ اللهِ — لَقَدْ أَلَحَّ فِي الدُّعَاء»\n\nنَتَائِجُ بَدْر:\n• قُتِلَ ٧٠ مِنَ القُرَيْشِ — أُسِرَ ٧٠\n• قُتِلَ أَبُو جَهْل (فِرْعَوْنُ الأُمَّة)\n• ﴿وَلَقَدْ نَصَرَكُمُ اللهُ بِبَدْرٍ وَأَنْتُمْ أَذِلَّة فَاتَّقُوا اللهَ لَعَلَّكُمْ تَشْكُرُون﴾",
"Battle of Badr (Ramadan 2 AH / 624 CE):\nMuslims: 313 — Quraysh: 1,000\n\nBefore the battle:\nProphet ﷺ raised his hands: 'O Allah, if this small group perishes, You will not be worshipped on earth' — until his cloak fell.\nAbu Bakr held his hand: 'Enough O Messenger of Allah — you have prayed earnestly.'\n\nResults of Badr:\n• 70 Quraysh killed, 70 captured\n• Abu Jahl killed (Pharaoh of this Ummah)\n• 'Allah has helped you at Badr when you were lowly — so fear Allah that you may be grateful.' [3:123]",
"يَوْمُ الفُرْقَان: بَدْرٌ كَانَ مُفْتَرَقَ الطُّرُق — قَبْلَهُ كَانَ المُسْلِمُون ضُعَفَاء مَظْلُومُون — بَعْدَهُ أَصْبَحُوا قُوَّة لَهَا كِيَان. المَلَائِكَة نَزَلَتْ تُقَاتِل — ﴿إِذْ تَسْتَغِيثُونَ رَبَّكُمْ فَاسْتَجَابَ لَكُمْ أَنِّي مُمِدُّكُمْ بِأَلْفٍ مِنَ المَلَائِكَة﴾",
[{arabic:"غَزْوَة",transliteration:"ghazwah",english:"battle (in which Prophet ﷺ participated)",pos:"noun (f)"},
 {arabic:"فُرْقَان",transliteration:"furqān",english:"criterion/distinguishing (Badr's name)",pos:"noun (m)"},
 {arabic:"أَسِير",transliteration:"asīr",english:"prisoner of war",pos:"noun (m)"},
 {arabic:"مَدَد",transliteration:"madad",english:"reinforcement/support (angels)",pos:"noun (m)"},
 {arabic:"اسْتِغَاثَة",transliteration:"istighāthah",english:"calling for help/relief",pos:"noun (f)"}],
{title:"The Theology of Victory at Badr",titleArabic:"لَاهُوتُ النَّصْرِ فِي بَدْر",
 explanation:"Badr teaches the Islamic formula for victory:\n1. Prepare all you can (أَعِدُّوا) — 313 were prepared\n2. Make du'a with sincerity and certainty\n3. Trust Allah with the result — the angels came\n\nQuran named Badr 'Yawm al-Furqan' — the Day of Criterion between truth and falsehood.\nEvery victory since then follows the same formula.",
 example:{arabic:"﴿وَمَا النَّصْرُ إِلَّا مِنْ عِنْدِ اللهِ﴾",translation:"'And victory is only from Allah.' [3:126] — The real source of Badr's outcome"}},
{q:"How many Muslims fought at Badr against how many Quraysh?",opts:["100 vs 500","313 vs 1,000","500 vs 1,000","313 vs 500"],a:1},
{q:"What does 'Yawm al-Furqan' (Day of Criterion) mean for Badr?",opts:["The day of fasting","The day that distinguished truth from falsehood — a turning point","The day of prayer","The day of peace"],a:1}),

mk("seerah-prophet-muhammad",9,"The Battle of Uhud — Lessons from Defeat","غَزْوَةُ أُحُد — دُرُوسُ الهَزِيمَة","The painful setback at Uhud and its eternal lessons about obedience, patience, and the wisdom of trials.",
"أُحُد (شَوَّال ٣ هـ / ٦٢٥ م):\n\nالسَّبَب: خِلَافُ الرُّمَاة — أَمَرَهُمُ النَّبِيُّ ﷺ: «لَا تَتْرُكُوا مَكَانَكُمْ وَلَوْ رَأَيْتُمُوا الطَّيْرَ تَخْطَفُنَا» — لَمَّا رَأَوُا الغَنِيمَة نَزَلُوا\nخَالِد بنُ الوَلِيد (قَبْلَ إِسْلَامِهِ) اسْتَغَلَّ الثَّغْرَة — هَاجَمَ مِنَ الخَلْف\n\nشَهِيدُ أُحُد:\nحَمْزَةُ بْنُ عَبْدِ المُطَّلِبِ — عَمُّ النَّبِيِّ ﷺ وَأَسَدُ اللهِ — يُمَثِّلُ بِجُثَّتِهِ وَحْشِيٌّ\nبَكَى النَّبِيُّ ﷺ: «لَنْ أُصَابَ بِمِثْلِكَ أَبَدًا»\n\n﴿وَلَا تَهِنُوا وَلَا تَحْزَنُوا وَأَنْتُمُ الأَعْلَوْنَ إِنْ كُنْتُمْ مُؤْمِنِين﴾ [آل عمران: ١٣٩]",
"Battle of Uhud (Shawwal 3 AH / 625 CE):\n\nThe cause: The archers' dispute — Prophet ﷺ commanded: 'Do not leave your position even if you see birds carrying us away.' — When they saw the spoils, they came down.\nKhalid ibn al-Walid (before his Islam) exploited the gap — attacked from behind.\n\nMartyr of Uhud:\nHamzah ibn Abd al-Muttalib — the Prophet's uncle and 'Lion of Allah' — his body mutilated by Wahshi.\nProphet ﷺ wept: 'I shall never suffer a loss like you.'\n\n'Do not weaken and do not grieve, and you will be superior if you are true believers.' [3:139]",
"القُرْآنُ خَصَّصَ ٦٠ آيَة لِأُحُد — لِأَنَّ الدَّرْسَ أَهَمّ مِنَ النَّصْر. «كَيْفَ تَنْصُرُونَ وَأَنْتُمْ تَعْصُونَ؟» — الطَّاعَةُ شَرْطُ النَّصْر، وَالصَّبْرُ عِنْدَ البَلَاءِ أَصْلُ الإِيمَان.",
[{arabic:"رَامٍ",transliteration:"rāmin",english:"archer (pl: رُمَاة)",pos:"noun (m)"},
 {arabic:"غَنِيمَة",transliteration:"ghanīmah",english:"war spoils",pos:"noun (f)"},
 {arabic:"ثَغْرَة",transliteration:"thughrah",english:"gap/breach (in defense)",pos:"noun (f)"},
 {arabic:"مُثْلَة",transliteration:"muthlah",english:"mutilation of a body",pos:"noun (f)"},
 {arabic:"بَلَاء",transliteration:"balāʾ",english:"trial/tribulation",pos:"noun (m)"}],
{title:"Why Did Allah Allow Uhud?",titleArabic:"لِمَاذَا أَذِنَ اللهُ بِأُحُد؟",
 explanation:"The Quran answered directly:\n1. 'That Allah might know who truly believed and who was hypocrite' [3:167]\n2. 'To distinguish the believers and take from among you martyrs' [3:140]\n3. 'To purify the believers and destroy the disbelievers' [3:141]\n\nUhud was NOT a failure — it was a divine curriculum:\n• Obedience must be unconditional\n• Spoils of this world must never distract\n• Trials are a graduation test, not a punishment",
 example:{arabic:"﴿أَمْ حَسِبْتُمْ أَنْ تَدْخُلُوا الجَنَّةَ وَلَمَّا يَعْلَمِ اللهُ الَّذِينَ جَاهَدُوا مِنْكُمْ﴾",translation:"'Did you think you would enter Paradise before Allah knows those who strove?' [3:142]"}},
{q:"Why did the Muslims lose the advantage at Uhud?",opts:["They were outnumbered","Some archers left their position for spoils, disobeying the Prophet's ﷺ order","The Quraysh had better weapons","The Prophet ﷺ made a military error"],a:1},
{q:"Who was called 'Asad Allah' (Lion of Allah) and was martyred at Uhud?",opts:["Abu Bakr RA","Umar RA","Hamzah ibn Abd al-Muttalib RA","Khalid ibn al-Walid"],a:2}),

mk("seerah-prophet-muhammad",10,"The Battle of the Trench (Ahzab)","غَزْوَةُ الخَنْدَق","The siege of Madinah — Salman al-Farisi's idea saves the Muslim community.",
"الأَحْزَاب (شَوَّال ٥ هـ / ٦٢٧ م):\nتَحَالَفَتِ القَبَائِل ضِدَّ المُسْلِمِين — ١٠٫٠٠٠ مُقَاتِل يُحَاصِرُون المَدِينَة\n\nفِكْرَةُ سَلْمَان الفَارِسِيّ: «فِي بِلَادِ فَارِس نَحْفِر خَنْدَقًا» — حَفَرَهُ الصَّحَابَة فِي سِتَّة أَيَّام — النَّبِيُّ ﷺ يَعْمَلُ مَعَهُم\n\nمُعْجِزَةُ الخَبَزِ: جَابِرٌ يَدْعُو النَّبِيَّ ﷺ لِطَعَامٍ قَلِيل — فَأَكَلَ مِنْهُ الجَيْشُ كُلُّه\n\nالرِّيَاح الإِلَهِيَّة: ﴿فَأَرْسَلْنَا عَلَيْهِمْ رِيحًا وَجُنُودًا لَمْ تَرَوْهَا﴾ [الأحزاب: ٩]\nالجَيْشُ تَفَرَّقَ بَعْدَ شَهْر مِنَ الحِصَار — دُونَ مَعْرَكَة كُبْرَى",
"The Trench (Ahzab — Shawwal 5 AH / 627 CE):\nTribes allied against Muslims — 10,000 fighters besiege Madinah\n\nSalman al-Farisi's idea: 'In Persia we dig a trench' — Companions dug in 6 days — Prophet ﷺ worked with them.\n\nMiracle of bread: Jabir invited Prophet ﷺ for a small meal — the entire army ate from it.\n\nDivine wind: 'We sent upon them a wind and armies you did not see.' [33:9]\nThe army dispersed after a month of siege — without a major battle.",
"النَّصْرُ بِالتَّدْبِير: الإِسْلَام يَأْخُذُ بِالأَسْبَاب — سَلْمَانُ الفَارِسِيُّ (الفَارِسِيُّ الأَصْل) أَنْقَذَ المَدِينَة بِعِلْمِهِ. «سَلْمَانُ مِنَّا آلَ البَيْت» — قَالَهُ النَّبِيُّ ﷺ. الجِنْسِيَّة فِي الإِسْلَام: التَّقْوَى لَا العِرْق.",
[{arabic:"خَنْدَق",transliteration:"khandaq",english:"trench/ditch",pos:"noun (m)"},
 {arabic:"حِصَار",transliteration:"ḥiṣār",english:"siege/blockade",pos:"noun (m)"},
 {arabic:"أَحْزَاب",transliteration:"aḥzāb",english:"confederates/factions",pos:"noun (m.pl)"},
 {arabic:"رِيح",transliteration:"rīḥ",english:"wind (divine weapon here)",pos:"noun (f)"},
 {arabic:"جُنُود",transliteration:"junūd",english:"armies/soldiers",pos:"noun (m.pl)"}],
{title:"Surah Al-Ahzab on the Battle",titleArabic:"سُورَةُ الأَحْزَابِ وَالغَزْوَة",
 explanation:"Surah 33 (Al-Ahzab) was largely revealed during this period:\n• 'And when the believers saw the Confederates, they said: This is what Allah and His Messenger promised us...' [33:22]\n• The believers passed the test — their fear was acknowledged but their Iman held\n• Allah's intervention: 'We sent a wind and armies you didn't see' — Quraysh's tents flew and fires extinguished",
 example:{arabic:"﴿فَأَرْسَلْنَا عَلَيْهِمْ رِيحًا وَجُنُودًا لَمْ تَرَوْهَا وَكَانَ اللهُ بِمَا تَعْمَلُونَ بَصِيرًا﴾",translation:"'We sent upon them a wind and armies you did not see — Allah is Seeing of what you do.' [33:9]"}},
{q:"Whose idea was it to dig the trench?",opts:["Abu Bakr RA","Umar RA","Salman al-Farisi RA","Ali RA"],a:2},
{q:"How did the siege of the Trench end?",opts:["A major battle","The Muslims surrendered","Divine wind dispersed the confederates","A peace treaty"],a:1}),

mk("seerah-prophet-muhammad",11,"The Treaty of Hudaybiyyah","صُلْحُ الحُدَيْبِيَّة","The 'apparent defeat' that was actually Islam's greatest diplomatic victory.",
"الحُدَيْبِيَّة (ذُو القَعْدَة ٦ هـ / ٦٢٨ م):\nالنَّبِيُّ ﷺ يَتَوَجَّهُ لِلعُمْرَة بِـ١٤٠٠ — يُوقَفُون\n\nشُرُوطُ الصُّلْح الظَّاهِرَة:\n• يَرْجِعُون هَذَا العَام\n• الهُدْنَة عَشْرُ سَنَوَات\n• مَنْ جَاءَ مِنَ المُسْلِمِين يُرَدّ — وَمَنْ هَرَبَ مِنَ المُشْرِكِين لَا يُرَدّ\n• يَكْتُبُ: «مُحَمَّدٌ» فَقَطْ (لَا «رَسُولُ اللهِ»)\n\nغَضَبُ الصَّحَابَة — عُمَرُ يَسْأَل: «أَلَسْنَا عَلَى الحَقّ؟» — «بَلَى» — «فَفِيمَ نُعْطِي الدَّنِيَّة فِي دِينِنَا؟»\n\n﴿إِنَّا فَتَحْنَا لَكَ فَتْحًا مُبِينًا﴾ [الفتح: ١] — نَزَلَتْ فِي طَرِيقِ العَوْدَة",
"Hudaybiyyah (Dhu'l-Qa'dah 6 AH / 628 CE):\nProphet ﷺ heading for Umrah with 1,400 — stopped.\n\nApparent disadvantageous terms:\n• Return this year\n• 10-year truce\n• Muslims who come — returned / Quraysh who flee — not returned\n• He writes 'Muhammad' only (not 'Messenger of Allah')\n\nCompanions angered — Umar asks: 'Aren't we on truth?' — 'Yes' — 'Then why give concession in our religion?'\n\n'We have given you a clear conquest.' [48:1] — revealed on the return journey.",
"الإِسْتِرَاتِيجِيَّة الرَّبَّانِيَّة: فِي سَنَتَيْن دَخَلَ أَكْثَرُ مِنَ الإِسْلَامِ فِي الإِسْلَامِ مِنَ العِشْرِين سَنَة السَّابِقَة (خَالِد وَعَمْرو وَأُلُوف) — السِّلْم خَيْرٌ مِنَ الحَرْب حِينَ يَخْدُمُ الدَّعْوَة.",
[{arabic:"صُلْح",transliteration:"ṣulḥ",english:"peace treaty",pos:"noun (m)"},
 {arabic:"هُدْنَة",transliteration:"hudnah",english:"truce/ceasefire",pos:"noun (f)"},
 {arabic:"دَنِيَّة",transliteration:"daniyyah",english:"concession/humiliation",pos:"noun (f)"},
 {arabic:"فَتْح",transliteration:"fatḥ",english:"conquest/opening (divine victory)",pos:"noun (m)"},
 {arabic:"مُبِين",transliteration:"mubīn",english:"clear/manifest",pos:"adjective"}],
{title:"How Hudaybiyyah was a 'Clear Conquest'",titleArabic:"كَيْفَ كَانَتِ الحُدَيْبِيَّة «فَتْحًا مُبِينًا»",
 explanation:"Two years of peace after Hudaybiyyah achieved more than 20 years of war:\n1. People could interact with Muslims freely → thousands embraced Islam\n2. Khalid ibn al-Walid — the greatest military genius — embraced Islam\n3. Amr ibn al-As embraced Islam\n4. The Prophet ﷺ could send letters to kings\n5. Quraysh violated the treaty first (attacking an ally tribe) → justifying Makkah's conquest\n\nSometimes Allah's 'defeat' is greater than human 'victory.'",
 example:{arabic:"﴿إِنَّا فَتَحْنَا لَكَ فَتْحًا مُبِينًا﴾",translation:"'Indeed We have granted you a clear conquest.' [48:1] — Allah called Hudaybiyyah a CONQUEST before Makkah was opened!"}},
{q:"What appeared to be a humiliating concession at Hudaybiyyah?",opts:["Paying ransom","Muslims must return this year without performing Umrah, and sent-back Muslims aren't returned","Fighting with fewer soldiers","Allowing Quraysh to attack allies"],a:1},
{q:"What great result came from the Hudaybiyyah peace period?",opts:["Muslims built a new city","Khalid ibn al-Walid and thousands more embraced Islam during the peace","The Ka'bah was rebuilt","Gold was distributed"],a:1}),

mk("seerah-prophet-muhammad",12,"Letters to Kings — The Global Call","رَسَائِلُ النَّبِيِّ ﷺ إِلَى المُلُوك","After Hudaybiyyah, the Prophet ﷺ sends letters to the world's rulers — Islam goes global.",
"الرَّسَائِل إِلَى المُلُوك:\n\n«بِسْمِ اللهِ الرَّحْمَنِ الرَّحِيمِ مِنْ مُحَمَّدٍ رَسُولِ اللهِ إِلَى هِرَقْلَ عَظِيمِ الرُّوم...\nأَسْلِمْ تَسْلَمْ يُؤْتِكَ اللهُ أَجْرَكَ مَرَّتَيْن...\n﴿يَا أَهْلَ الكِتَابِ تَعَالَوْا إِلَى كَلِمَةٍ سَوَاءٍ بَيْنَنَا وَبَيْنَكُمْ...﴾»\n\nمَنْ أَرْسَلَ إِلَيْهِمْ:\n• هِرَقْل — امبراطور الروم (شَهِدَ لِصِدْقِ الرِّسَالَة لَكِنْ لَمْ يُسْلِم)\n• كِسْرَى — مَلِكُ فَارِس (مَزَّقَ الرِّسَالَة — تَمَزَّقَتْ مَمْلَكَتُهُ)\n• النَّجَاشِيّ — مَلِكُ الحَبَشَة (أَسْلَمَ — صَلَّى عَلَيْهِ النَّبِيُّ ﷺ غَائِبًا)\n• المُقَوْقِسُ — مَلِكُ مِصْر (أَهْدَى لَكِنْ لَمْ يُسْلِم)\n• الحَارِثُ الغَسَّانِيّ وَغَيْرُهُم",
"Letters to Kings:\n\n'In the name of Allah, the Most Gracious, the Most Merciful. From Muhammad, the Messenger of Allah, to Heraclius, the Great of Rome... Submit, and you will have peace — Allah will give you double reward... [3:64]'\n\nTo whom letters were sent:\n• Heraclius — Emperor of Rome (testified to the truth but didn't embrace Islam)\n• Khosrow — King of Persia (tore the letter — his kingdom was torn)\n• Al-Najashi — King of Abyssinia (embraced Islam — Prophet ﷺ prayed over him in absentia)\n• Al-Muqawqis — King of Egypt (sent gifts but didn't embrace Islam)\n• Al-Harith al-Ghassani and others",
"النَّبِيُّ ﷺ فَكَّرَ عَالَمِيًّا مِنْ يَوْم ١: «أَرْسَلْتُ إِلَى الأَحْمَرِ وَالأَسْوَد» (لِكُلِّ البَشَر). الرِّسَالَةُ مَعَهُ اليَوْم: خَاتَمُهُ الَّذِي خَتَمَ بِهِ الرَّسَائِل مَوْجُودٌ فِي مُتْحَفِ قَاهِرَة.",
[{arabic:"هِرَقْل",transliteration:"hiraqil",english:"Heraclius (Emperor of Rome)",pos:"proper noun"},
 {arabic:"كِسْرَى",transliteration:"kisrā",english:"Khosrow (King of Persia)",pos:"proper noun"},
 {arabic:"نَجَاشِيّ",transliteration:"najāshiyy",english:"Al-Najashi (King of Abyssinia)",pos:"proper noun"},
 {arabic:"أَسْلِمْ تَسْلَمْ",transliteration:"aslim taslam",english:"Submit and you will have peace (opening of letters)",pos:"phrase"},
 {arabic:"خَاتَم",transliteration:"khātam",english:"seal/signet ring",pos:"noun (m)"}],
{title:"The Letter to Heraclius — Evidence of Prophethood",titleArabic:"رِسَالَةُ هِرَقْل — دَلِيلٌ عَلَى النُّبُوَّة",
 explanation:"Abu Sufyan (before his Islam) was in Rome when Heraclius questioned him:\n'Does anyone who becomes Muslim ever abandon it?' — Abu Sufyan: 'No.'\nHeraclius: 'That is true faith.'\n\nHeraclius recognized the signs of a prophet in the letter. He said to his courtiers: 'If I could reach him, I would wash his feet.' But he feared losing his kingdom and didn't embrace Islam.\n\nThe letter of the Prophet ﷺ to Heraclius was found in the Vatican — preserved for 1,400 years.",
 example:{arabic:"«أَسْلِمْ تَسْلَمْ يُؤْتِكَ اللهُ أَجْرَكَ مَرَّتَيْن»",translation:"'Submit to Islam and you will have peace — Allah will give you your reward twice.' — Opening formula of the letters to kings"}},
{q:"Which king tore up the Prophet's letter, resulting in his kingdom being torn?",opts:["Heraclius","Al-Najashi","Khosrow (Kisra) of Persia","Al-Muqawqis of Egypt"],a:2},
{q:"Which of the kings embraced Islam and was prayed over by the Prophet ﷺ in absentia?",opts:["Heraclius","Al-Najashi of Abyssinia","Khosrow","Al-Muqawqis"],a:1}),

mk("seerah-prophet-muhammad",13,"The Conquest of Makkah","فَتْحُ مَكَّةَ المُكَرَّمَة","The most powerful moment in Seerah — the Prophet ﷺ enters Makkah with 10,000 and offers general amnesty.",
"فَتْحُ مَكَّة (رَمَضَان ٨ هـ / ٦٣٠ م):\n١٠٠٠٠ مُقَاتِل — مَشَى النَّبِيُّ ﷺ عَلَى رَاحِلَتِهِ مُطَأْطِئًا رَأْسَهُ شُكْرًا للهِ\n\nأَعْظَمُ لَحَظَة:\nوَقَفَ عِنْدَ بَابِ الكَعْبَة — أَهْلُ مَكَّةَ مُجْتَمِعُون — يَنْتَظِرُون حُكْمَهُ:\n«يَا مَعْشَرَ قُرَيْش مَا تَظُنُّونَ أَنِّي فَاعِلٌ بِكُمْ؟»\n«خَيْرًا — أَخٌ كَرِيمٌ وَابْنُ أَخٍ كَرِيم»\n«اذْهَبُوا فَأَنْتُمُ الطُّلَقَاء»\n\nكَسَرَ الأَصْنَام وَقَرَأَ: ﴿وَقُلْ جَاءَ الحَقُّ وَزَهَقَ البَاطِلُ إِنَّ البَاطِلَ كَانَ زَهُوقًا﴾ [الإسراء: ٨١]",
"Conquest of Makkah (Ramadan 8 AH / 630 CE):\n10,000 fighters — Prophet ﷺ rode with his head bowed in gratitude to Allah.\n\nThe Greatest Moment:\nStood at the Ka'bah door — people of Makkah gathered — awaiting his judgement:\n'O Quraysh — what do you think I will do to you?'\n'Good — a noble brother and the son of a noble brother.'\n'Go — you are all free.'\n\nSmashed the idols reciting: 'Say: Truth has come and falsehood has departed — falsehood was always bound to depart.' [17:81]",
"«الطُّلَقَاء» — أَعْظَمُ عَفْوٍ فِي التَّارِيخ: الَّذِينَ عَذَّبُوا بِلَالًا وَمَزَّقُوا جَسَدَ حَمْزَة وَأَخْرَجُوا النَّبِيَّ مِنْ مَكَّة — كُلُّهُمْ عُفِيَ عَنْهُمْ. هَذَا هُوَ الإِسْلَام — رَحْمَةٌ لِلْعَالَمِين.",
[{arabic:"فَتْح",transliteration:"fatḥ",english:"conquest/opening (bloodless victory)",pos:"noun (m)"},
 {arabic:"طُلَقَاء",transliteration:"ṭulaqāʾ",english:"freed ones (those granted amnesty)",pos:"noun (m.pl)"},
 {arabic:"عَفْو",transliteration:"ʿafw",english:"pardon/general amnesty",pos:"noun (m)"},
 {arabic:"زَهَقَ",transliteration:"zahaqa",english:"has vanished/departed (falsehood)",pos:"verb (past)"},
 {arabic:"صَنَم",transliteration:"ṣanam",english:"idol",pos:"noun (m)"}],
{title:"The Mercy of the Conquest — ʿĀm al-Raḥmah",titleArabic:"رَحْمَةُ الفَتْح — عَامُ الرَّحْمَة",
 explanation:"The conquest of Makkah is unique in world history:\n• No looting, no killing of innocents\n• General amnesty for 21 years of persecution\n• Bilal called the Adhan from the Ka'bah — the former slave on top of Islam's holiest site\n\nNapoleon, Alexander, Caesar — all conquered by force and installed domination.\nThe Prophet ﷺ conquered by mercy — and installed brotherhood.\n\nWithin 2 years, Makkah had more sincere Muslims than 18 years of preaching produced.",
 example:{arabic:"«اذْهَبُوا فَأَنْتُمُ الطُّلَقَاء»",translation:"'Go — you are all free.' — The Prophet ﷺ to his 20-year oppressors. The most magnanimous moment in human history."}},
{q:"What did the Prophet ﷺ declare when his oppressors awaited judgment after the Conquest?",opts:["Imprisonment for the leaders","'Go — you are all free (Tulaqa)' — general amnesty","Death for Abu Sufyan","Exile from Makkah"],a:1},
{q:"Who called the Adhan from the Ka'bah on the day of the Conquest?",opts:["Abu Bakr RA","Umar RA","Bilal ibn Rabah RA","Ali RA"],a:2}),

mk("seerah-prophet-muhammad",14,"The Farewell Hajj & Final Sermon","حَجَّةُ الوَدَاعِ وَالخُطْبَةُ الأَخِيرَة","The Prophet's ﷺ final pilgrimage and his comprehensive parting message to humanity.",
"حَجَّةُ الوَدَاع (ذُو الحِجَّة ١٠ هـ / ٦٣٢ م):\nقَرَابَةُ ١١٤٠٠٠ حَاجّ مَعَهُ\n\nأَبْرَزُ الخُطْبَة:\n«أَيُّهَا النَّاسُ إِنَّ دِمَاءَكُمْ وَأَمْوَالَكُمْ وَأَعْرَاضَكُمْ عَلَيْكُمْ حَرَامٌ كَحُرْمَةِ يَوْمِكُمْ هَذَا فِي شَهْرِكُمْ هَذَا فِي بَلَدِكُمْ هَذَا»\n\n«لَا تَرْجِعُوا بَعْدِي كُفَّارًا يَضْرِبُ بَعْضُكُمْ رِقَابَ بَعْض»\n\n«تَرَكْتُ فِيكُمْ مَا لَنْ تَضِلُّوا بَعْدَهُ إِنْ اعْتَصَمْتُمْ بِهِ: كِتَابَ اللهِ وَسُنَّتِي»\n\n«أَلَا هَلْ بَلَّغْتُ؟» — «اللَّهُمَّ اشْهَدْ» — ثَلَاثَ مَرَّات\n\nنَزَلَتْ: ﴿اليَوْمَ أَكْمَلْتُ لَكُمْ دِينَكُمْ﴾",
"Farewell Hajj (Dhu'l-Hijjah 10 AH / 632 CE):\nAbout 114,000 pilgrims with him\n\nCore points of the sermon:\n'Your blood, wealth, and honor are sacred to you — as sacred as this day, in this month, in this land.'\n\n'Do not revert after me to disbelievers striking each other's necks.'\n\n'I leave among you what if you hold to, you will never go astray: the Book of Allah and my Sunnah.'\n\n'Have I conveyed?' — 'O Allah, be Witness!' — three times\n\nRevealed: 'This day I have perfected for you your religion.' [5:3]",
"﴿اليَوْمَ أَكْمَلْتُ لَكُمْ دِينَكُمْ﴾ — عُمَرُ بَكَى عِنْدَمَا سَمِعَهَا: «إِنَّهُ لَيْسَ بَعْدَ الكَمَالِ إِلَّا النُّقْصَان» — فَعَرَفَ أَنَّ النَّبِيَّ ﷺ سَيَرْحَل قَرِيبًا. هَذَا كَانَ قَبْلَ ٨٠ يَوْمًا مِنْ وَفَاتِهِ ﷺ.",
[{arabic:"حَجَّةُ الوَدَاع",transliteration:"ḥajjatu l-wadāʿ",english:"Farewell Pilgrimage",pos:"proper noun"},
 {arabic:"بَلَّغَ",transliteration:"ballagha",english:"conveyed/delivered (the message)",pos:"verb (past)"},
 {arabic:"اعْتَصَمَ",transliteration:"iʿtaṣama",english:"held firmly to/clung to",pos:"verb (past)"},
 {arabic:"أَكْمَلَ",transliteration:"akmala",english:"completed/perfected",pos:"verb (past)"},
 {arabic:"رَقَبَة",transliteration:"raqabah",english:"neck (metaphor for killing)",pos:"noun (f)"}],
{title:"'This Day I Have Perfected Your Religion'",titleArabic:"«اليَوْمَ أَكْمَلْتُ لَكُمْ دِينَكُمْ» — دَلَالَتُهَا",
 explanation:"Verse 5:3 — revelation at Arafah during Farewell Hajj:\n\nA Jewish man said to Umar: 'If this verse were revealed to us, we would make that day a festival.'\nUmar responded: 'We know which day and where it was revealed — on a Friday, the Day of Arafah.'\n\nThe verse means:\n• No new religion is needed after Islam\n• No commandment of Islam was left undelivered\n• The Prophet ﷺ completed his mission\n• A signal of approaching farewell",
 example:{arabic:"﴿اليَوْمَ أَكْمَلْتُ لَكُمْ دِينَكُمْ وَأَتْمَمْتُ عَلَيْكُمْ نِعْمَتِي وَرَضِيتُ لَكُمُ الإِسْلَامَ دِينًا﴾",translation:"'This day I have perfected your religion, completed My favor upon you, and approved Islam as your religion.' [5:3]"}},
{q:"How many pilgrims approximately accompanied the Prophet ﷺ on the Farewell Hajj?",opts:["3,000","10,000","50,000","About 114,000"],a:3},
{q:"'I leave among you two things — hold to them and you won't go astray.' What are they?",opts:["Prayer and fasting","The Quran and the Sunnah of the Prophet ﷺ","Zakat and Hajj","The Quran and the Companions"],a:1}),

mk("seerah-prophet-muhammad",15,"The Death of the Prophet ﷺ","وَفَاةُ النَّبِيِّ ﷺ","The most difficult day in Islamic history — and how the companions navigated it.",
"وَفَاتُهُ ﷺ (١٢ رَبِيع الأَوَّل ١١ هـ / ٨ يُونِيو ٦٣٢ م):\nالمَرَضُ بَدَأَ بَعْدَ رُجُوعِهِ مِنَ البَقِيع — حُمَّى شَدِيدَة\nطَلَبَ أَنْ يُصَلِّيَ النَّاسَ عِنْدَ أَبِي بَكْرٍ\n\nآخِرُ لَحَظَاتِهِ:\nرَفَعَ إِصْبَعَهُ إِلَى السَّمَاء: «اللَّهُمَّ الرَّفِيقَ الأَعْلَى» ← اخْتَارَ لِقَاءَ اللهِ\n\nأَبُو بَكْرٍ:\n«مَنْ كَانَ يَعْبُدُ مُحَمَّدًا فَإِنَّ مُحَمَّدًا قَدْ مَات — وَمَنْ كَانَ يَعْبُدُ اللهَ فَإِنَّ اللهَ حَيٌّ لَا يَمُوت»\n﴿وَمَا مُحَمَّدٌ إِلَّا رَسُولٌ قَدْ خَلَتْ مِنْ قَبْلِهِ الرُّسُل﴾\n\nعُمَرُ سَقَطَ مِنَ الصَّدْمَة — ثُمَّ هَدَأَ بِكَلَامِ أَبِي بَكْر",
"His death ﷺ (12 Rabi' al-Awwal 11 AH / June 8, 632 CE):\nIllness began after visiting Al-Baqi' — severe fever.\nAsked that Abu Bakr lead people in prayer.\n\nFinal moments:\nRaised his finger to the sky: 'O Allah, the Highest Companion (Al-Rafiq al-A'la)' ← chose to meet Allah.\n\nAbu Bakr:\n'Whoever worshipped Muhammad — Muhammad has died. Whoever worshipped Allah — Allah is Living and does not die.'\n'Muhammad is but a messenger; before him messengers have passed.' [3:144]\n\nUmar collapsed in shock — then calmed by Abu Bakr's words.",
"الأُمَّةُ لَمْ تَمُتْ بِوَفَاتِهِ ﷺ — لِأَنَّ رِسَالَتَهُ كَامِلَة — لِأَنَّ الكِتَابَ مَحْفُوظ — لِأَنَّ الصَّحَابَة وَرِثُوا. «حُزْنُنَا عَلَيْهِ دَلِيلُ مَحَبَّتِنَا — وَمَحَبَّتُنَا وَاجِبَة»",
[{arabic:"وَفَاة",transliteration:"wafāh",english:"death/passing (respectful term)",pos:"noun (f)"},
 {arabic:"رَفِيق الأَعْلَى",transliteration:"ar-rafīq al-aʿlā",english:"The Highest Companion (Allah) — his last words",pos:"noun phrase"},
 {arabic:"حُمَّى",transliteration:"ḥummā",english:"fever",pos:"noun (f)"},
 {arabic:"خَلَتْ",transliteration:"khalat",english:"have passed (before, speaking of messengers)",pos:"verb (past)"},
 {arabic:"صَدْمَة",transliteration:"ṣadmah",english:"shock/trauma",pos:"noun (f)"}],
{title:"Abu Bakr's Response — The Greatest Moment of Leadership",titleArabic:"رَدُّ أَبِي بَكْرٍ — أَعْظَمُ لَحَظَةِ قِيَادَة",
 explanation:"When Umar was saying 'He has not died' in denial, Abu Bakr's response was:\n1. Quran 3:144 — every messenger before passed away\n2. Clear logic: if you worshipped Muhammad, he died. If you worshipped Allah, Allah is eternal.\n3. He didn't deny grief — he channeled it\n\nThe Prophet ﷺ had prepared Abu Bakr for this moment by having him lead prayers during his illness.\nAl-Siddiq (the truthful) proved his title at the hardest possible moment.",
 example:{arabic:"«مَنْ كَانَ يَعْبُدُ مُحَمَّدًا فَإِنَّ مُحَمَّدًا قَدْ مَاتَ وَمَنْ كَانَ يَعْبُدُ اللهَ فَإِنَّ اللهَ حَيٌّ لَا يَمُوت»",translation:"'Whoever worshipped Muhammad — Muhammad has died. Whoever worshipped Allah — Allah is Living and does not die.' — Abu Bakr's words that stabilized the Ummah"}},
{q:"What were the Prophet's ﷺ last words as he pointed to the sky?",opts:["Allahu Akbar","La ilaha illa Allah","O Allah, the Highest Companion (Al-Rafiq al-A'la)","SubhanAllah"],a:2},
{q:"What verse did Abu Bakr recite to stabilize the companions after the Prophet's ﷺ death?",opts:["Al-Fatiha","'Muhammad is but a messenger; before him messengers have passed' [3:144]","Ayat al-Kursi","'Every soul will taste death' [3:185]"],a:1}),

...Array.from({length:25},(_,i)=>i+16).map(n=>mk(
  "seerah-prophet-muhammad", n,
  ["His Physical Description","His Moral Character","His Generosity & Compassion","His Worship & Night Prayers",
   "His Miracles","His Treatment of Women","His Treatment of Non-Muslims",
   "His Relationships with Companions","His Love for Children",
   "The Prophet's Household","The Four Rightly-Guided Caliphs — Overview",
   "Abu Bakr's Caliphate","Umar's Caliphate","Uthman's Caliphate","Ali's Caliphate",
   "Lessons from the Seerah for Today","The Seerah and Modern Challenges",
   "Emulating the Prophet ﷺ","The Prophet ﷺ in the Quran",
   "Loving the Prophet ﷺ — Signs and Requirements","Du'a and Salawat on the Prophet",
   "The Prophet ﷺ in Hadith Collections","Seerah Resources and Further Study",
   "Review: Early Makkan Period","Review: Madinan Period and Legacy"][n-16]||`Seerah Lesson ${n}`,
  ["الوَصْفُ الجِسْمِيّ","الأَخْلَاقُ الرَّفِيعَة","الكَرَمُ وَالرَّحْمَة","العِبَادَةُ وَقِيَامُ اللَّيْل",
   "المُعْجِزَات","مَعَامَلَتُهُ لِلمَرْأَة","مَعَامَلَتُهُ لِغَيْرِ المُسْلِمِين",
   "عَلَاقَتُهُ بِالصَّحَابَة","حُبُّهُ لِلأَطْفَال",
   "آلُ بَيْتِ النَّبِيِّ","الخُلَفَاءُ الرَّاشِدُون — مُقَدِّمَة",
   "خِلَافَةُ أَبِي بَكْر","خِلَافَةُ عُمَر","خِلَافَةُ عُثْمَان","خِلَافَةُ عَلِيّ",
   "دُرُوسُ السِّيرَةِ اليَوْم","السِّيرَةُ وَتَحَدِّيَاتُ العَصْر",
   "الاقْتِدَاءُ بِالنَّبِيِّ ﷺ","النَّبِيُّ ﷺ فِي القُرْآن",
   "مَحَبَّةُ النَّبِيِّ ﷺ — عَلَامَاتُهَا وَمُتَطَلَّبَاتُهَا","الدُّعَاءُ وَالصَّلَاةُ عَلَى النَّبِيّ",
   "النَّبِيُّ ﷺ فِي كُتُبِ الحَدِيث","مَصَادِرُ السِّيرَة",
   "مُرَاجَعَة: العَهْدُ المَكِّيّ","مُرَاجَعَة: العَهْدُ المَدَنِيّ"][n-16]||`الدَّرْسُ ${n}`,
  `Lesson ${n} — deepening understanding of the Prophet's ﷺ life, character, and legacy.`,
  `الدَّرْسُ ${n}: دِرَاسَةٌ مُتَعَمِّقَة لِحَيَاةِ النَّبِيِّ ﷺ\n\n﴿لَقَدْ كَانَ لَكُمْ فِي رَسُولِ اللهِ أُسْوَةٌ حَسَنَةٌ لِمَنْ كَانَ يَرْجُو اللهَ وَاليَوْمَ الآخِرَ وَذَكَرَ اللهَ كَثِيرًا﴾ [الأحزاب: ٢١]\n\nقَالَ الإِمَامُ القُسْطَلَّانِيّ: «لَا أُبَالِي بَعْدَ حُبِّكَ — مِنْ شَيْء»\n\nدِرَاسَةُ السِّيرَة فَرِيضَة — لِأَنَّهَا الدَّلِيلُ التَّطْبِيقِيُّ عَلَى القُرْآن.`,
  `Lesson ${n} — in-depth study of the Prophet's ﷺ life.\n\n'There has certainly been for you in the Messenger of Allah an excellent pattern — for one who hopes in Allah and the Last Day.' [33:21]\n\nStudying the Seerah is an act of worship — it is the practical guide to the Quran.`,
  `هَذَا الدَّرْسُ يُعَمِّقُ مَعْرِفَتَنَا بِالنَّبِيِّ ﷺ — مَنْ عَرَفَهُ أَحَبَّهُ — وَمَنْ أَحَبَّهُ اتَّبَعَهُ — وَمَنِ اتَّبَعَهُ نَجَا.`,
  [{arabic:"سِيرَة",transliteration:"sīrah",english:"biography/life story",pos:"noun (f)"},
   {arabic:"أُسْوَة",transliteration:"uswah",english:"model/example",pos:"noun (f)"},
   {arabic:"رِسَالَة",transliteration:"risālah",english:"message/prophethood",pos:"noun (f)"},
   {arabic:"صَحَابِيّ",transliteration:"ṣaḥābiyy",english:"companion of the Prophet",pos:"noun (m)"},
   {arabic:"إِرْث",transliteration:"irth",english:"heritage/legacy",pos:"noun (m)"}],
  {title:"The Seerah as Tafsir",titleArabic:"السِّيرَةُ تَفْسِيرٌ لِلْقُرْآن",
   explanation:`The Seerah and Quran are inseparable:\n• Most of the Quran was revealed in response to events in the Prophet's ﷺ life\n• Understanding the Seerah = understanding the Quran in context\n• Aisha RA said: 'His character was the Quran' — the Seerah IS the Quran lived\n\nLesson ${n} continues building this comprehensive understanding.`,
   example:{arabic:"«كَانَ خُلُقُهُ القُرْآن» — السَّيِّدَةُ عَائِشَة رَضِيَ اللهُ عَنْهَا",translation:"'His character was the Quran.' — Aisha RA describing the Prophet ﷺ"}},
  {q:`What is the key Quranic verse about following the Prophet ﷺ as a model?`,opts:["Al-Fatiha 1:1","Al-Ahzab 33:21 — 'There has been for you in the Messenger an excellent pattern'","Al-Baqarah 2:2","An-Nisa 4:1"],a:1},
  {q:`Studying the Seerah is important because:`,opts:["It's only for scholars","It brings us closer to the Prophet ﷺ, strengthens Iman, and is the lived example of the Quran","It only matters for Arabic speakers","It's historical curiosity"],a:1}
)),

// ── SEERAH COMPANIONS — Lessons 3–30 ──────────────────────────────────────

mk("seerah-companions",3,"Uthman ibn Affan RA — Dhu an-Nurain","عُثْمَانُ بْنُ عَفَّان ﵂ — ذُو النُّورَيْن","Twice married to the Prophet's daughters. His generosity, compilation of Quran, and martyrdom.",
"عُثْمَانُ بْنُ عَفَّانٍ رَضِيَ اللهُ عَنْهُ:\n\n• «ذُو النُّورَيْن» — تَزَوَّجَ رُقَيَّة ﵂ — ثُمَّ بَعْدَ وَفَاتِهَا أُمَّ كُلْثُوم ﵂\n\n• كَرَمُهُ: جَهَّزَ جَيْشَ العُسْرَة بِأَلْفِ بَعِير وَمَاتِعٍ — قَالَ النَّبِيُّ ﷺ: «مَا ضَرَّ عُثْمَانَ مَا عَمِلَ بَعْدَ اليَوْم»\n\n• جَمْعُ القُرْآن: أَشْرَفَ عَلَى جَمْعِ المُصْحَف الإِمَام — أَوَّلُ مُصْحَف مُوَحَّد\n\n• الشَّهَادَة: حُوصِرَ ٤٠ يَوْمًا — رَفَضَ أَنْ يُسَلَّ عَلَيْهِ السَّيْف — قُتِلَ وَهُوَ يَقْرَأُ القُرْآن\nقَالَ: «اللَّهُمَّ لَا تُسَلِّطْ عَلَيْهِمْ بِسَيْفِهِمْ» — دُعَاؤُهُ عَلَى نَفْسِهِ بِالمَغْفِرَة لِقَاتِلِيه",
"Uthman ibn Affan RA:\n• 'Dhu an-Nurain' — married Ruqayyah RA, then after her death Umm Kulthum RA (both Prophet's daughters)\n• Generosity: outfitted the Army of Hardship with 1,000 camels — Prophet ﷺ: 'Nothing Uthman does after today can harm him'\n• Compilation of Quran: oversaw compilation of the unified Mushaf — first standardized copy\n• Martyrdom: besieged 40 days — refused to allow blood drawn on his behalf — killed while reading Quran\nHe said: 'O Allah do not give them authority by the sword' — he prayed for his killers to be forgiven",
"أَعْظَمُ خِدْمَاتِهِ: الجَمْعُ الَّذِي نَقْرَأُهُ اليَوْم — مُصْحَفُنَا مَنْسُوبٌ إِلَيْهِ. شَهَادَتُهُ كَانَتْ إِيثَارًا: كَانَ يَقْدِرُ عَلَى الدِّفَاع وَاخْتَارَ عَدَم سَفْكِ الدِّمَاء.",
[{arabic:"ذُو النُّورَيْن",transliteration:"dhū n-nūrayn",english:"The One with Two Lights (his title)",pos:"proper noun"},
 {arabic:"مُصْحَف",transliteration:"muṣḥaf",english:"compiled written Quran",pos:"noun (m)"},
 {arabic:"جَيْشُ العُسْرَة",transliteration:"jaysh al-ʿusrah",english:"Army of Hardship (Tabuk expedition)",pos:"proper noun"},
 {arabic:"حِصَار",transliteration:"ḥiṣār",english:"siege",pos:"noun (m)"},
 {arabic:"شَهَادَة",transliteration:"shahādah",english:"martyrdom",pos:"noun (f)"}],
{title:"The Uthman Mushaf — Our Quran Today",titleArabic:"مُصْحَفُ عُثْمَان — قُرْآنُنَا اليَوْم",
 explanation:"The Mushaf (written Quran) standardization:\n• After the Prophet's ﷺ death: memorized by companions\n• Abu Bakr: first WRITTEN collection (after Battle of Yamama — 70+ huffaz martyred)\n• Uthman: standardized ONE version with vowel markings, destroyed dialect variations\n\nResult: 1,400 years later — every Quran in the world is identical.\nThis is the Uthman Mushaf — our connection to Uthman's blessed work.",
 example:{arabic:"«جَمَعَ عُثْمَانُ النَّاسَ عَلَى مُصْحَفٍ وَاحِد — فَكَانَ مِنْ أَعْظَمِ مَا قَدَّمَهُ لِلإِسْلَام»",translation:"'Uthman united people on one Mushaf — it was among the greatest things he gave to Islam.'"}},
{q:"Why is Uthman RA called 'Dhu an-Nurain' (Two Lights)?",opts:["He owned two lamps","He married two of the Prophet's daughters","He memorized two parts of Quran","He led two battles"],a:1},
{q:"What was Uthman's RA greatest contribution to the preservation of the Quran?",opts:["Memorizing it entirely","Compiling and standardizing the unified written Mushaf used worldwide","Writing the first commentary","Teaching it in schools"],a:1}),

mk("seerah-companions",4,"Ali ibn Abi Talib RA — The Lion of Allah","عَلِيُّ بْنُ أَبِي طَالِبٍ ﵂ — أَسَدُ اللهِ","Raised in the Prophet's home. Knowledge, bravery, wisdom, and his role as Fourth Caliph.",
"عَلِيُّ بْنُ أَبِي طَالِبٍ رَضِيَ اللهُ عَنْهُ:\n\n• رُبِّيَ فِي بَيْتِ النَّبِيِّ ﷺ مُنْذُ الصِّغَر\n• أَوَّلُ مَنْ أَسْلَمَ مِنَ الصِّبْيَان\n• نَامَ فِي فِرَاشِهِ ﷺ لَيْلَةَ الهِجْرَة — جَرَأَة نَادِرَة\n• قَالَ فِيهِ النَّبِيُّ ﷺ: «أَنَا دَارُ الحِكْمَةِ وَعَلِيٌّ بَابُهَا»\n• حَامِلُ رَايَة خَيْبَر: «لَأُعْطِيَنَّهَا رَجُلًا يُحِبُّ اللهَ وَرَسُولَهُ وَيُحِبُّهُ اللهُ وَرَسُولُهُ»\n• الخَلِيفَةُ الرَّابِع — زَمَنُهُ فِيهِ الفِتَن — صَبَرَ وَحَكَمَ بِالعَدْل\n• شَهَادَتُهُ: طُعِنَ فِي الفَجْرِ — تُوُفِّيَ ٢١ رَمَضَان ٤٠ هـ",
"Ali ibn Abi Talib RA:\n• Raised in the Prophet's ﷺ home from childhood\n• First boy to embrace Islam\n• Slept in the Prophet's bed on the night of Hijrah — extraordinary courage\n• Prophet ﷺ about him: 'I am the House of Wisdom and Ali is its Door'\n• Bearer of the flag at Khaybar: 'I will give it to a man who loves Allah and His Messenger and they love him'\n• Fourth Caliph — his era full of trials — he persevered and ruled with justice\n• Martyrdom: stabbed at Fajr — died 21 Ramadan 40 AH",
"الإِمَامُ أَحْمَد: «مَا جَاءَ فِي أَحَدٍ مِنَ الصَّحَابَةِ مَا جَاءَ فِي عَلِيّ» — أَكْثَرُهُمْ فَضَائِلَ مَذْكُورَة فِي الحَدِيث. حُبُّهُ إِيمَانٌ — بُغْضُهُ نِفَاق.",
[{arabic:"فِتْنَة",transliteration:"fitnah",english:"trial/civil strife",pos:"noun (f)"},
 {arabic:"رَايَة",transliteration:"rāyah",english:"flag/banner",pos:"noun (f)"},
 {arabic:"بَاب الحِكْمَة",transliteration:"bāb al-ḥikmah",english:"Gate of Wisdom (Ali's title)",pos:"proper noun"},
 {arabic:"الخَلِيفَة الرَّابِع",transliteration:"al-khalīfah ar-rābiʿ",english:"The Fourth Caliph",pos:"noun phrase"},
 {arabic:"إِيمَان",transliteration:"īmān",english:"faith (loving Ali is sign of Iman)",pos:"noun (m)"}],
{title:"Ali's RA Knowledge — Dar al-Hikmah",titleArabic:"عِلْمُ عَلِيٍّ ﵂ — دَارُ الحِكْمَة",
 explanation:"'I am the City of Knowledge and Ali is its Gate' [attributed, some scholars authenticate it]\n\nAli's RA knowledge encompassed:\n• Quran and Tafsir\n• Fiqh — many rulings trace to him\n• Nahw (Arabic grammar) — said to have founded it\n• Khutab (sermons) — Nahj al-Balagha collection\n\nIbn Abbas learned Quran interpretation from Ali RA directly.\nThe Prophet ﷺ taught Ali specifically in private sessions.",
 example:{arabic:"«أَنَا دَارُ الحِكْمَةِ وَعَلِيٌّ بَابُهَا»",translation:"'I am the House of Wisdom and Ali is its Gate.' — The Prophet ﷺ about Ali RA"}},
{q:"What was Ali RA's role on the Night of Hijrah?",opts:["He traveled with the Prophet","He slept in the Prophet's bed to mislead the plotters — risking his own life","He guarded the Ka'bah","He warned the Ansar"],a:1},
{q:"Ali RA was assassinated:",opts:["After Fajr prayer in the mosque during Ramadan","During the Battle of Uhud","At Hajj","In Makkah"],a:0}),

...Array.from({length:26},(_,i)=>i+5).map(n=>mk(
  "seerah-companions", n,
  ["Khadijah bint Khuwaylid RA","Aisha bint Abi Bakr RA","Bilal ibn Rabah RA","Salman al-Farisi RA",
   "Abu Dharr al-Ghifari RA","Hamzah ibn Abd al-Muttalib RA","Khalid ibn al-Walid RA",
   "Mus'ab ibn Umayr RA","Abdullah ibn Masud RA","Ammar ibn Yasir RA",
   "Zayd ibn Haritha RA","Fatimah al-Zahra RA","Umm Salamah RA",
   "Asma bint Abi Bakr RA","Abu Hurayrah RA","Abdullah ibn Abbas RA",
   "Sa'd ibn Abi Waqqas RA","Abd al-Rahman ibn Awf RA","Abu Ubayda ibn al-Jarrah RA",
   "Muadh ibn Jabal RA","Hudhayfah ibn al-Yaman RA","Usama ibn Zayd RA",
   "Sumayyah bint Khabbat RA — First Martyr","The Ansar — Helpers of Madinah",
   "The Muhajirun — Migrants of Makkah","Final Reflection on the Companions"][n-5]||`Companion ${n}`,
  ["خَدِيجَةُ بِنْتُ خُوَيْلِد","عَائِشَةُ بِنْتُ أَبِي بَكْر","بِلَالُ بْنُ رَبَاح","سَلْمَانُ الفَارِسِيّ",
   "أَبُو ذَرٍّ الغِفَارِيّ","حَمْزَةُ بْنُ عَبْدِ المُطَّلِب","خَالِدُ بْنُ الوَلِيد",
   "مُصْعَبُ بْنُ عُمَيْر","عَبْدُ اللهِ بْنُ مَسْعُود","عَمَّارُ بْنُ يَاسِر",
   "زَيْدُ بْنُ حَارِثَة","فَاطِمَةُ الزَّهْرَاء","أُمُّ سَلَمَة",
   "أَسْمَاءُ بِنْتُ أَبِي بَكْر","أَبُو هُرَيْرَة","عَبْدُ اللهِ بْنُ عَبَّاس",
   "سَعْدُ بْنُ أَبِي وَقَّاص","عَبْدُ الرَّحْمَنِ بْنُ عَوْف","أَبُو عُبَيْدَةَ بْنُ الجَرَّاح",
   "مُعَاذُ بْنُ جَبَل","حُذَيْفَةُ بْنُ اليَمَان","أُسَامَةُ بْنُ زَيْد",
   "سُمَيَّةُ بِنْتُ خَبَّاط — أَوَّلُ شَهِيدَة","الأَنْصَار","المُهَاجِرُون","الخَاتِمَة: الصَّحَابَة الكِرَام"][n-5]||`الدَّرْسُ ${n}`,
  `Life and legacy of this great companion — lessons for the modern Muslim.`,
  `الدَّرْسُ ${n}: حَيَاةُ الصَّحَابِيِّ الكَرِيم وَإِرْثُهُ\n\n«الصَّحَابَةُ كَالنُّجُوم — بِأَيِّهِمُ اقْتَدَيْتُمُ اهْتَدَيْتُمْ»\n\nكُلُّ صَحَابِيٍّ حَمَلَ شُعْلَةَ الإِسْلَامِ فِي عَصْرِهِ — وَأَوْصَلَهَا إِلَيْنَا.`,
  `Lesson ${n}: The life of this noble companion and their legacy.\n\n'The Companions are like stars — whichever you follow, you will be guided.'\n\nEach companion carried the torch of Islam in their era and passed it to us.`,
  `عَاشُوا لِلَّهِ وَمَاتُوا لِلَّهِ — وَبَقِيَ ذِكْرُهُمْ حَتَّى يَوْمِ القِيَامَة.`,
  [{arabic:"صَحَابِيّ",transliteration:"ṣaḥābiyy",english:"companion of the Prophet ﷺ",pos:"noun (m)"},
   {arabic:"تَابِعِيّ",transliteration:"tābiʿiyy",english:"follower (of a companion)",pos:"noun (m)"},
   {arabic:"سِيرَة",transliteration:"sīrah",english:"biography/life story",pos:"noun (f)"},
   {arabic:"فَضِيلَة",transliteration:"faḍīlah",english:"virtue/excellence/merit",pos:"noun (f)"},
   {arabic:"إِرْث",transliteration:"irth",english:"heritage/legacy",pos:"noun (m)"}],
  {title:"Learning from the Companions",titleArabic:"التَّعَلُّمُ مِنَ الصَّحَابَة",
   explanation:`The companions were:\n• Real people with families, fears, and imperfections\n• Chosen to carry the message in its most critical era\n• Their strength came from their proximity to the Prophet ﷺ\n\nFor lesson ${n}, study this companion deeply:\n• What test did they face?\n• How did they respond?\n• What can we apply today?`,
   example:{arabic:"﴿وَالسَّابِقُونَ الأَوَّلُونَ مِنَ المُهَاجِرِينَ وَالأَنْصَارِ وَالَّذِينَ اتَّبَعُوهُمْ بِإِحْسَانٍ رَضِيَ اللهُ عَنْهُمْ وَرَضُوا عَنْهُ﴾",translation:"'The forerunners — the first of the Muhajirun and Ansar and those who followed them in righteousness — Allah is pleased with them and they are pleased with Him.' [9:100]"}},
  {q:`Which companions receive guaranteed divine pleasure according to Quran 9:100?`,opts:["Only the four caliphs","The Muhajirun, Ansar, and all who followed them in righteousness","Only the 10 promised Paradise","Only Badr companions"],a:1},
  {q:`Loving the companions is:`,opts:["Optional","Part of following Islam completely — they preserved and transmitted it","Only for scholars","Cultural preference"],a:1}
)),

// ── ISLAMIC HISTORY — Lessons 2–25 ────────────────────────────────────────

mk("seerah-islamic-history",2,"The Caliphate of Abu Bakr Al-Siddiq","خِلَافَةُ أَبِي بَكْرٍ الصِّدِّيق","Two years that prevented Islam's collapse — the Riddah Wars and the first written Quran.",
"أَبُو بَكْرٍ الصِّدِّيقُ — خَلِيفَة (١١–١٣ هـ / ٦٣٢–٦٣٤ م):\n\nتَحَدِّيَاتُ الخِلَافَة:\n١. حُرُوبُ الرِّدَّة: قَبَائِل ارْتَدَّتْ وَمَنَعَتِ الزَّكَاة — قَالَ: «وَاللهِ لَأُقَاتِلَنَّ مَنْ فَرَّقَ بَيْنَ الصَّلَاةِ وَالزَّكَاة» — خَالِدُ بْنُ الوَلِيد يَقُودُ الجُيُوش\n٢. مُسَيْلِمَة الكَذَّاب: اسْتُشْهِدَ فِي حَرْبِهِ ٧٠ حَافِظًا → جَمَعَ القُرْآن\n٣. جَيْشُ أُسَامَة: أَنْفَذَهُ رَغْمَ الضَّغُوط — احْتِرَامُ أَوَامِرِ النَّبِيِّ ﷺ\n\nخُطْبَتُهُ الأُولَى: «أَيُّهَا النَّاسُ إِنِّي قَدْ وُلِّيتُ عَلَيْكُمْ وَلَسْتُ بِخَيْرِكُمْ — فَإِنْ رَأَيْتُمُونِي عَلَى حَقٍّ فَأَعِينُونِي وَإِنْ رَأَيْتُمُونِي عَلَى بَاطِلٍ فَقَوِّمُونِي»",
"Abu Bakr Al-Siddiq — Caliph (11–13 AH / 632–634 CE):\n\nChallenges of Caliphate:\n1. Riddah Wars: tribes apostatized and refused Zakah — he said: 'By Allah, I will fight those who separate prayer from Zakah' — Khalid ibn al-Walid led armies\n2. Musaylimah the Liar: 70 Quran memorizers martyred in battle against him → led to Quran's first written compilation\n3. Army of Usama: dispatched despite pressure — respecting the Prophet's ﷺ orders\n\nFirst Sermon: 'O people — I have been appointed over you though I am not the best of you. If you see me doing right, support me. If you see me doing wrong, correct me.'",
"أَبُو بَكْرٍ جَمَعَ الأُمَّة بِقُوَّة الإِيمَانِ لَا بِقُوَّةِ السَّيْف — خِلَافَتُهُ ٢ سَنَة وَنِصْف غَيَّرَتْ مَسَارَ التَّارِيخ: رَسَّخَ الخِلَافَة، حَفِظَ القُرْآن، وَبَدَأَ الفُتُوحَات.",
[{arabic:"رِدَّة",transliteration:"riddah",english:"apostasy (leaving Islam)",pos:"noun (f)"},
 {arabic:"خِلَافَة",transliteration:"khilāfah",english:"caliphate (political leadership)",pos:"noun (f)"},
 {arabic:"حَافِظ",transliteration:"ḥāfiẓ",english:"memorizer of Quran",pos:"noun (m)"},
 {arabic:"مُسَيْلِمَة",transliteration:"musaylimah",english:"the false prophet (liar)",pos:"proper noun"},
 {arabic:"زَكَاة",transliteration:"zakāh",english:"compulsory charity",pos:"noun (f)"}],
{title:"Separation of Salah and Zakah — Abu Bakr's Greatest Decision",titleArabic:"قِرَانُ الصَّلَاةِ وَالزَّكَاة — أَعْظَمُ قَرَارِ أَبِي بَكْر",
 explanation:"Tribes said: 'We pray but won't pay Zakah.'\nMany companions (including Umar) said: 'Leave them — they testify the Shahada.'\nAbu Bakr: 'The Prophet established prayer AND Zakah together. By Allah I will fight those who separate them.'\n\nThis decision:\n1. Established that Zakah is non-negotiable like prayer\n2. Set precedent for authority of established Sunnah\n3. Preserved Islamic law as a complete system\n4. Umar later said: 'I then realized Abu Bakr was right.'",
 example:{arabic:"«وَاللهِ لَأُقَاتِلَنَّ مَنْ فَرَّقَ بَيْنَ الصَّلَاةِ وَالزَّكَاة — فَإِنَّ الزَّكَاةَ حَقُّ المَال»",translation:"'By Allah, I will fight whoever separates prayer from Zakah — for Zakah is the right of wealth.' — Abu Bakr's decisive ruling"}},
{q:"What was the key mistake made by some tribes after the Prophet's ﷺ death?",opts:["They stopped praying","They refused to pay Zakah claiming it was only owed to the Prophet","They left Makkah","They stopped fasting"],a:1},
{q:"Why did the Riddah Wars lead to the first written compilation of the Quran?",opts:["Abu Bakr ordered it from the start","70+ Quran memorizers were martyred in the wars — threatening to lose Quran memorization","The Prophet ﷺ ordered it before death","Umar suggested it"],a:1}),

...Array.from({length:23},(_,i)=>i+3).map(n=>mk(
  "seerah-islamic-history", n,
  ["The Caliphate of Umar ibn al-Khattab","The Caliphate of Uthman ibn Affan","The Caliphate of Ali ibn Abi Talib",
   "The Umayyad Dynasty — Rise","Islam in Persia and Central Asia",
   "The Islamic Conquest of North Africa","Al-Andalus — Islam in Spain",
   "The Abbasid Caliphate and Golden Age","Islamic Science and Learning",
   "The Crusades — Muslim Response","The Mongol Invasion",
   "The Mamluk Sultanate — Defenders of Islam","The Ottoman Empire — Rise",
   "The Ottoman Caliphate — Peak","Islam in West Africa — The Empires",
   "Islam in Southeast Asia","Islam in the Indian Subcontinent",
   "The Colonial Period and Muslim Decline","Islamic Revival Movements — 18th-19th Century",
   "The Fall of the Ottoman Caliphate (1924)","Islam in the Modern Nation-State",
   "Muslim Minorities in the West","Final Lesson: Islam and the Contemporary World"][n-3]||`History Lesson ${n}`,
  ["خِلَافَةُ عُمَرَ بْنِ الخَطَّاب","خِلَافَةُ عُثْمَانَ بْنِ عَفَّان","خِلَافَةُ عَلِيِّ بْنِ أَبِي طَالِب",
   "الدَّوْلَةُ الأُمَوِيَّة — النَّشَأَة","الإِسْلَامُ فِي فَارِسَ وَآسْيَا الوُسْطَى",
   "الفَتْحُ الإِسْلَامِيُّ لِشِمَالِ إِفْرِيقِيَا","الأَنْدَلُس — الإِسْلَامُ فِي الأَسْبَان",
   "الدَّوْلَةُ العَبَّاسِيَّة وَالعَصْرُ الذَّهَبِيّ","العِلْمُ وَالتَّعَلُّمُ الإِسْلَامِيّ",
   "الحُرُوبُ الصَّلِيبِيَّة وَالرَّدُّ الإِسْلَامِيّ","الغَزْوُ المَغُولِيّ",
   "دَوْلَةُ المَمَالِيك — حُمَاةُ الإِسْلَام","الدَّوْلَةُ العُثْمَانِيَّة — النَّشْأَة",
   "الخِلَافَةُ العُثْمَانِيَّة — الذُّرْوَة","الإِسْلَامُ فِي غَرْبِ إِفْرِيقِيَا",
   "الإِسْلَامُ فِي جَنُوبِ شَرْقِ آسِيَا","الإِسْلَامُ فِي شِبْهِ القَارَّةِ الهِنْدِيَّة",
   "الحِقْبَةُ الاسْتِعْمَارِيَّة وَانْحِطَاطُ المُسْلِمِين","حَرَكَاتُ الصُّحُوَةِ الإِسْلَامِيَّة",
   "سُقُوطُ الخِلَافَةِ العُثْمَانِيَّة (١٩٢٤)","الإِسْلَامُ فِي الدَّوْلَةِ القَوْمِيَّة الحَدِيثَة",
   "المُسْلِمُون الأَقَلِّيَّاتُ فِي الغَرْب","خَاتِمَة: الإِسْلَامُ وَالعَالَمُ المُعَاصِر"][n-3]||`الدَّرْسُ ${n}`,
  `Islamic history lesson ${n} — understanding how Islam shaped civilization and faced trials.`,
  `الدَّرْسُ ${n}: التَّارِيخُ الإِسْلَامِيّ\n\n«التَّارِيخُ مَدْرَسَةُ الأُمَم» — إِبْنُ خَلْدُون\n\nالتَّارِيخُ الإِسْلَامِيُّ لَيْسَ مَجَرَّدَ أَحْدَاث — بَلْ هُوَ إِثْبَاتٌ لِوَعْدِ اللهِ بِنَصْرِ الدِّين.\n﴿وَعَدَ اللهُ الَّذِينَ آمَنُوا مِنْكُمْ وَعَمِلُوا الصَّالِحَاتِ لَيَسْتَخْلِفَنَّهُمْ فِي الأَرْضِ﴾`,
  `Lesson ${n}: Islamic history — understanding how Islam shaped civilization and faced trials.\n\n'History is the school of nations.' — Ibn Khaldun\n\nIslamic history is not mere events — it is proof of Allah's promise to support the religion.`,
  `دِرَاسَةُ التَّارِيخِ الإِسْلَامِيِّ تُقَوِّي الإِيمَانَ وَتُعَلِّمُ الدُّرُوس — كَيْفَ صَعِدَتِ الأُمَّة وَكَيْفَ سَقَطَتْ وَكَيْفَ تَعُود.`,
  [{arabic:"خِلَافَة",transliteration:"khilāfah",english:"caliphate/Islamic governance",pos:"noun (f)"},
   {arabic:"فُتُوحَات",transliteration:"futūḥāt",english:"conquests/openings",pos:"noun (f.pl)"},
   {arabic:"حَضَارَة",transliteration:"ḥaḍārah",english:"civilization",pos:"noun (f)"},
   {arabic:"انْحِطَاط",transliteration:"inḥiṭāṭ",english:"decline/fall",pos:"noun (m)"},
   {arabic:"نَهْضَة",transliteration:"nahḍah",english:"renaissance/awakening",pos:"noun (f)"}],
  {title:"The Cyclical Pattern of Islamic History",titleArabic:"النَّمَطُ الدَّوْرِيُّ فِي التَّارِيخِ الإِسْلَامِيّ",
   explanation:`Ibn Khaldun's theory of civilization applies to Islamic history:\n1. Rise: Strong Iman + Unity + 'Asabiyyah (solidarity)\n2. Peak: Great civilization, science, scholarship\n3. Decline: Luxury, division, distance from Quran\n4. Reform: A mujaddid (renewer) calls to revival\n\nLesson ${n} demonstrates this cycle with specific historical examples.`,
   example:{arabic:"﴿وَعَدَ اللهُ الَّذِينَ آمَنُوا مِنْكُمْ وَعَمِلُوا الصَّالِحَاتِ لَيَسْتَخْلِفَنَّهُمْ فِي الأَرْض﴾",translation:"'Allah has promised those who believe and do righteous deeds that He will make them successors on earth.' [24:55]"}},
  {q:`What is the primary lesson of studying Islamic history?`,opts:["Islam is only for Arabs","Islamic civilization has proven that Iman + action produces great civilizations — and neglect causes decline","History has no lessons for today","Muslims must always be in conflict"],a:1},
  {q:`Ibn Khaldun's theory about civilizations states:`,opts:["They only rise","They follow a cycle of rise, peak, decline, and potential revival","They only fall","Arabian civilizations are superior"],a:1}
)),

];
