import { Router } from "express";
import healthRouter from "./health";
import profileRouter from "./profile";
import surahsRouter from "./surahs";
import progressRouter from "./progress";
import recordingsRouter from "./recordings";
import bookmarksRouter from "./bookmarks";
import achievementsRouter from "./achievements";
import dashboardRouter from "./dashboard";
import leaderboardRouter from "./leaderboard";
import transcribeRouter from "./transcribe";
import teacherRouter from "./teacher";
import hifdhRouter from "./hifdh";
import voiceTeacherRouter from "./voice-teacher";
import studyPlannerRouter from "./study-planner";
import adminRouter from "./admin";
import teacherDashboardRouter from "./teacher-dashboard";
import libraryRouter from "./library";

const router = Router();

router.use(healthRouter);
router.use(profileRouter);
router.use(surahsRouter);
router.use(progressRouter);
router.use(recordingsRouter);
router.use(bookmarksRouter);
router.use(achievementsRouter);
router.use(dashboardRouter);
router.use(leaderboardRouter);
router.use(transcribeRouter);
router.use(teacherRouter);
router.use(hifdhRouter);
router.use(voiceTeacherRouter);
router.use(studyPlannerRouter);
router.use(adminRouter);
router.use(teacherDashboardRouter);
router.use(libraryRouter);

export default router;
