import { Router } from "express";
import healthRouter from "./health";
import profileRouter from "./profile";
import surahsRouter from "./surahs";
import progressRouter from "./progress";
import recordingsRouter from "./recordings";
import bookmarksRouter from "./bookmarks";
import achievementsRouter from "./achievements";
import dashboardRouter from "./dashboard";
import leaderboardRouter from "./leaderboard";
import transcribeRouter from "./transcribe";
import teacherRouter from "./teacher";
import hifdhRouter from "./hifdh";
import voiceTeacherRouter from "./voice-teacher";
import studyPlannerRouter from "./study-planner";
import adminRouter from "./admin";
import teacherDashboardRouter from "./teacher-dashboard";
import libraryRouter from "./library";
import examsRouter from "./exams";
import certificatesRouter from "./certificates";
import cmsRouter from "./cms";
import parentRouter from "./parent";
import analyticsRouter from "./analytics";
import notificationsRouter from "./notifications";
import videoTeacherRouter from "./video-teacher";
import contentGeneratorRouter from "./content-generator";
import messagesRouter from "./messages";
import paymentsRouter from "./payments";
import liveClassroomRouter from "./live-classroom";
import analyticsReportsRouter from "./analytics-reports";
import auditRouter from "./audit";
import marketingRouter from "./marketing";
import ttsRouter from "./tts";
import mushafRecitationRouter from "./mushaf-recitation";
import arabicLessonsRouter from "./arabic-lessons";

const router = Router();

router.use(healthRouter);
router.use(profileRouter);
router.use(surahsRouter);
router.use(progressRouter);
router.use(recordingsRouter);
router.use(bookmarksRouter);
router.use(achievementsRouter);
router.use(dashboardRouter);
router.use(leaderboardRouter);
router.use(transcribeRouter);
router.use(teacherRouter);
router.use(hifdhRouter);
router.use(voiceTeacherRouter);
router.use(studyPlannerRouter);
router.use(adminRouter);
router.use(teacherDashboardRouter);
router.use(libraryRouter);
router.use(examsRouter);
router.use(certificatesRouter);
router.use(cmsRouter);
router.use(parentRouter);
router.use(analyticsRouter);
router.use(notificationsRouter);
router.use(videoTeacherRouter);
router.use(contentGeneratorRouter);
router.use(messagesRouter);
router.use(paymentsRouter);
router.use(liveClassroomRouter);
router.use(analyticsReportsRouter);
router.use(auditRouter);
router.use(marketingRouter);
router.use(ttsRouter);
router.use(mushafRecitationRouter);
router.use(arabicLessonsRouter);

export default router;
